### ISSUE TITLE
Prestashop 8

### ISSUE THREAD

**Issue by Kandax86** [Oksydan/falcon#125]
Hi, i tried to install your theme and modules to prestashop 8 beta but it seems its not compatible, some abstract functions had been added and so the module can't be installed.
Do you plan to make it compliant with prestashop 8?

Thank you in advance

Cedric

**Comment by Oksydan** [comment]
Hi @Kandax86,

for some reason I didn't get notification about this issue in `is_themecore` module. 
This issue has been transferred to starter project.

Yes, version 3.0 is WIP atm and will it be available probably with 8.0 prestashop release. 
Thank you for your issue ❤️

**Comment by Oksydan** [comment]
Hi @Kandax86,

problem has been fixed. 
New version of `is_themecore` will be released with 3.0.0 version of starter.

**Comment by Oksydan** [comment]
New version has been released. 
I am closing this issue.
