### ISSUE TITLE
🐛 [BUG] - Typo in product-cover-thumbnails.tpl

### ISSUE THREAD

**Issue by develobora** [Oksydan/falcon#158]
### Description

Typo in `product-cover-thumbnails.tpl ` file in section `.product-main-images` - is `positon-relative`, should be `position-relative`. 

### Node.js version

v14.17.3

### php version

v7.4

### OS and it's version

Ubuntu 22.04

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to 'themes/starter/templates/catalog/_partials/product-cover-thumbnails.tpl'
3. Scroll down to '56 line'
4. See error
```

**Comment by Oksydan** [comment]
Hi @develobora,

thank you for creating an issue.
I was able to reproduce problem. 
That `.product-main-images` provides `position: relatives` via styles. 
We can get rid of id in in favore of just proper utility class.
It is more like improvement but I will add this to `3.0.1` roadmap.

**Comment by Oksydan** [comment]
hi @develobora,

new minor version has been released https://github.com/Oksydan/falcon/releases/tag/v3.0.1
I am closing this issue.
