### ISSUE TITLE
🚀 [REQUEST] - Add partytown

### ISSUE THREAD

**Issue by StefanVonRanda** [Oksydan/falcon#159]
### Summary

Please consider adding the partytown library to Falcon.

It a js library that makes it easy to load javascript asynchronously using web workers.

This, to me, would make it ideal for loading things like Google Tag Manager, Facebook Pixel and other analytics scripts in the background.

I hope you'll consider adding it to the theme or is_theme module, if it makes sense for you to do so.

### Feature target required module/theme

theme

### Drawbacks

A selection of possible drawbacks from partytowns website.

- Firing too many network requests to multiple servers. The more requests a site has to make, the longer it can take to load.
- Third-party scripts also often use embed techniques that can block `window.onload`, even if the embed is using async or defer.
- Third-party scripts that were loaded without care can be a single-point of failure (SPOF).

**Comment by Oksydan** [comment]
Hi @StefanVonRanda 

Thank you for creating an issue.
I was reading recently about partytown but since it is beta I didn't give it a try. 
I will try consider implementing it in next version. I will add an exrra switch in is_themecore disabled by default.

**Comment by Oksydan** [comment]
Hi @StefanVonRanda,

partytown feature has been added to is_themecore. 
New version has been released you can read about how to use it [here](https://github.com/Oksydan/is_themecore#partytown).

I am closing this issue, thank you ❤️
