### ISSUE TITLE
🐛 [BUG] - Error in the payment gateway module: Modal checkout

### ISSUE THREAD

**Issue by usuariorenzo** [Oksydan/falcon#161]
### Description

Hello,

I have problems running a payment gateway module called mercadopago, I have tried it in prestashop 8.0 and 1.7.x with this theme and the result is the same, it does not run the modal and there are problems in the css. I look forward to your correction in the next update, thank you.

Excellent theme
![image](https://user-images.githubusercontent.com/34630323/210705587-06233a99-d37b-444f-b9df-c66cb1026298.png)

![image](https://user-images.githubusercontent.com/34630323/210706821-e5c1a622-f6b0-41ae-889c-f8391c0f64cb.png)

### Node.js version

14.1.0

### php version

7.4

### OS and it's version

Win11

### Browsers

Firefox, Chrome, Safari

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

**Comment by Oksydan** [comment]
Hi @usuariorenzo,

Due to fact that this theme is more like developer tool not ready to use theme I am not going to try to solve problem with every third party module.
I was thinking about bringing back 1 checkout option per line and that is something I can do to solve your problem partially.

**Comment by Oksydan** [comment]
Hi @usuariorenzo,

like I said before i am not going to fix problem with third party module but with version 3.1.0 checkout options will be single line. It should help us avoid situations described above with module extra content isn't displayed properly.
