### ISSUE TITLE
🚀 [REQUEST] - Sticky header

### ISSUE THREAD

**Issue by eveneme** [Oksydan/falcon#168]
### Summary

A good addition would be Adding a sticky header at the top of the window.

### Feature target required module/theme

Theme

### Drawbacks

sticky menu when scrolling

**Comment by Oksydan** [comment]
Hi @eveneme,

that's actually good idea.
I will consider adding it in next minor update.

**Comment by Oksydan** [comment]
Hi @eveneme,

sticky header has been added on develop branch.
It will be available with next release.
