### ISSUE TITLE
🐛 [BUG] - button filtr is not displayed correctly

### ISSUE THREAD

**Issue by eveneme** [Oksydan/falcon#169]
### Description

![received_1157372301581129](https://user-images.githubusercontent.com/85762221/212540814-32d7d887-1c07-49df-883d-bc79229c85ac.jpeg)

### Node.js version

Latest

### php version

8.0

### OS and it's version

No

### Required module/theme

Theme

### Reproduction steps

```bash
Look screenshoot
```

**Comment by Oksydan** [comment]
HI @eveneme,

thank you for creating an issue.
I was able to reproduce an issue it will be fixed in next minor update.

**Comment by Oksydan** [comment]
Hi @eveneme,

bug has been fixed on develop branch and it's waiting for release.

**Comment by Oksydan** [comment]
Hi @eveneme,

new version has been released with the fix.
I am closing this issue.
