### ISSUE TITLE
🐛 [BUG] - Duplicate icons on address

### ISSUE THREAD

**Issue by ytilotti** [Oksydan/falcon#170]
### Description

The icons are duplicate on edit and delete actions.

An example:
![image](https://user-images.githubusercontent.com/5848945/212558054-73c77bf5-e55c-4a26-a016-4b823feda640.png)

### Node.js version

v14.21.1

### php version

v74

### OS and it's version

Docker

### Browsers

Chrome

### Required module/theme

theme v3

### Reproduction steps

```bash
1. Go to a product in front office
2. Make an order
3. Complete step 1, 2 & 3.
4. Go back to 3
```

**Comment by Oksydan** [comment]
Hi @ytilotti,

thank you for reporting an issue and for PR.

**Comment by Oksydan** [comment]
Hi @ytilotti,

new version 3.0.2 has been released. 
I am closing this issue since it has been resolved in new version.

Thank you for creating an issue and PR.
