### ISSUE TITLE
Prestshop Checkout module not working

### ISSUE THREAD

**Issue by gaetzone** [Oksydan/falcon#180]
### Description

Hi,
Prestashop Checkout module is working fine with the Classic theme but not with Starter/Falcon theme.

When "Pay by credit card" is checked, credit card fields are not displayed.
Here is the module documentation : https://github.com/PrestaShopCorp/ps_checkout/wiki/PrestaShop-Checkout---theme-customization

I found in DevTools that the ps_checkoutHostedFieldsEnabled variable is "false" whereas it should be "true". 
When Classic theme is activated,  ps_checkoutHostedFieldsEnabled variable is "true". 
Do you have an idea ?

Best regards

### Node.js version

16.17.0

### php version

7.4

### OS and it's version

Ubuntu

### Browsers

Firefox

### Required module/theme

no

### Reproduction steps

```bash
1. Prestashop checkout module is installed, activated and well configurated
2. Add to card a product
3. Go to checkout
4. Choose pay by credit card
```

### Logs

```bash
var ps_checkoutHostedFieldsEnabled = false;
```

**Comment by gaetzone** [comment]
I am really confused 
Trouble come from checkout/payment templates overide in child theme.
This was breaking the the process
Sorry for inconvenience

**Comment by onursonmez** [comment]
I have same issue. Credit card form is not showing :(
