### ISSUE TITLE
🚀 [REQUEST] - Increasing the default width

### ISSUE THREAD

**Issue by eveneme** [Oksydan/falcon#181]
### Summary

Increasing the default width of the template. It doesn't look good on full hd screens.

### Feature target required module/theme

theme

### Drawbacks

Increasing the default width of the template. It doesn't look good on full hd screens.

**Comment by Oksydan** [comment]
Hi @eveneme,

it's starter theme, not complete product ready to be deployed. 
If you need wider container you can just add another breakpoint to your container map. 
In bootstrap 5 by default there is wider container it will change then. 
For now I don't see point in this change.
