### ISSUE TITLE
🐛 [BUG] - Cart update quantity unavalaible

### ISSUE THREAD

**Issue by ytilotti** [Oksydan/falcon#182]
### Description

The update JS on cart page not working completely

### Node.js version

v14.21

### php version

v7.4

### OS and it's version

Docker

### Browsers

Chrome

### Required module/theme

theme v3

### Reproduction steps

```bash
1. Go to front
2. Add a product in the cart
3. Go to the cart
4. Add a big quantity (unavalaible)
5. The error not appear, refresh of page is necessary
```

**Comment by Oksydan** [comment]
Hi @ytilotti,

thank you for creating an issue and PR.
I was able to reproduce an issue.

**Comment by Oksydan** [comment]
Hi @ytilotti,

new version has been released.
Thank you for your contribution.
