### ISSUE TITLE
🚀 [REQUEST] - How to start develop

### ISSUE THREAD

**Issue by d0niek** [Oksydan/falcon#185]
### Summary

Hi @Oksydan!

Thank you for a great work you've done here!

I have a question and sorry I did it here.

How to start develop my own theme base on this one and stay open for any updates/upgrades you're doing here?

- Should I just install `falcon` and create my theme as a child? Here PS developers don't recommend that https://devdocs.prestashop-project.org/1.7/themes/reference/template-inheritance/parent-child-feature/
- Should I edit css styles only and don't touch html files?

### Feature target required module/theme

theme

### Drawbacks

...

**Comment by Oksydan** [comment]
Hi @d0niek ,
I recommend to you to build theme with it not on top of it with child theme. You are going to lose a lot of features if you are going to develop it as child theme. It's starter theme.

**Comment by d0niek** [comment]
Ok. So should I change only css files? On which parts should I look out to allow next update/upgrade go smooth?

**Comment by Oksydan** [comment]
You can change whatever you want. It's starter theme, there will be no easy way to upgrade. You can always compare two version and apply required changes.

**Comment by d0niek** [comment]
Ok. it's not a "theme framework"? It's like a [prestashop module generator](https://validator.prestashop.com/generator) where I got starter files and after that I start changing them to fit my needs.

I think we can close it.

**Comment by Oksydan** [comment]
Thanks @d0niek for creating an issue.
I am closing this issue. 
If you need any help or got problem with theme please create another issue.
