### ISSUE TITLE
🚀 [REQUEST] - blockwhishlist

### ISSUE THREAD

**Issue by glukash** [Oksydan/falcon#188]
### Summary

Hi
Will it be possible to make the blockwishlist module start to work in all versions?

### Feature target required module/theme

theme

### Drawbacks

No drawbacks.

**Comment by Oksydan** [comment]
HI @glukash,

I am not going to make blockwishlist module working with theme.
You can make it by your own.
Blockwishlist only js files only contains more code than my whole theme. 
I am not recommending using it. 

I am going to close it. Feel free to create another issue you find any problem with theme.
