### ISSUE TITLE
🐛 [BUG] - With webp enabled feature all html characters are escaped 

### ISSUE THREAD

**Issue by tomasz3k** [Oksydan/falcon#197]
### Description

Hello, 
I found very anoying bug with is_themcore module with webp feature enabled.
It use hookActionOutputHTMLBefore to change all html of a site with new links and other stuff.
After that all text entities are escaped so it is not longer possible to use translated strings in javascript.
For example ź is` &#378;`  ą is `&#261;`  ę is `&#281;` it looks very bad so I spend a lot of time to find a solution to correct this behavior.

Solution is to add`<meta http-equiv="content-type" content="text/html;charset=utf-8">` to the head_charset block of template in templates/_partials/head.tpl file so DomDocument will no escape characters anymore. 

Thanks 

### Node.js version

v18.12.1

### php version

v7.4

### OS and it's version

local dev ubuntu

### Required module/theme

is_themecore

### Reproduction steps

```bash
1. enable webp in is_themecore module
2. Take a look of page source and you will find escaped entities
```

**Comment by Oksydan** [comment]
Hi @tomasz3k,

Thank you for creating an issue.
I was able to reproduce problem. 

I will try to find solution to this problem and I will come back to you with information.

**Comment by tomasz3k** [comment]
Solution is to add`<meta http-equiv="content-type" content="text/html;charset=utf-8"> `to the head_charset block of template in templates/_partials/head.tpl file so DomDocument will no escape characters anymore.

**Comment by Oksydan** [comment]
That sound more like workaround not like proper solution. 
We should find solution that will can be extracted to another service and make use of `DOMDocument` that return properly decoded document.

**Comment by tomasz3k** [comment]
Sounds great. Good luck

**Comment by Oksydan** [comment]
Hi @tomasz3k,

new version of is_themecore module has been released.
For prestashop 8.0 - 3.0.2
and for prestashop < 8.0 - 2.3.2.

I am closing this issue. 
Thank you for your report.

**Comment by tomasz3k** [comment]
Thank you for updated version of the is_themecore module. 
Have a nice day and God bless!
