### ISSUE TITLE
Swiper loop previous slide

### ISSUE THREAD

**Issue by L-desmarets** [Oksydan/falcon#198]
### Description

Hello,

if you use loop sliding on Swiper modifying 'ProductGallery.js' with llop: true, the previous slide once on the first slide is empty whereas if you use the next button it is correctly displayed.

### Node.js version

8.5.0

### php version

v7.4

### OS and it's version

MAcOS Ventura

### Browsers

Firefox, Chrome

### Required module/theme

Falcon theme

### Reproduction steps

```bash
1. Go to '_Dev/js/components/ProductGallery.j'
2. Modify line 89, add loop: true,
3. npm run dev 
4. clic on a mutliple images product zoom for modal view
5. clic on product zoom for modal view
6. clic the left button
```

### Logs

```bash
src=`data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='800' viewBox='0 0 1 1'%3E%3C/svg%3E`
```

**Comment by Oksydan** [comment]
Hi @L-desmarets,

that's not a but. 
If you are modifying code you have to adjust it also in your gallery to make sure that indexes are set right. 

I am closing this one.
Feel free to open new one issue if you find any problems.
