### ISSUE TITLE
🐛 [BUG] - Backdrop remain if modal is opened twice

### ISSUE THREAD

**Issue by quddoss** [Oksydan/falcon#199]
### Description

When you click the "Add to Cart" button from different products in a row, 1 modal window appears as the end result, but when you click "Continue shopping" , only the second modal window closes and backdrop from firt modal remains.

[![recording.gif](https://s10.gifyu.com/images/recording.gif)](https://gifyu.com/image/S7oul)

### Node.js version

v14.21.2

### php version

8.1

### OS and it's version

Windows 11

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to products
2. Click on 'Add to cart' on different products
3. Close the modal after opened ...
```

**Comment by Oksydan** [comment]
HI @quddoss,

I was able to reproduce problem.
Thank you for creating an issue.

**Comment by Oksydan** [comment]
Hi @quddoss,

problem has been resolved and it's waiting for release.

**Comment by Oksydan** [comment]
Hi @quddoss,

new version has been released with the fix.
Thank you for creating an issue.
I am closing this one.
