### ISSUE TITLE
🐛 [BUG] - is_imageslider configuration problem in multi store multi language context

### ISSUE THREAD

**Issue by cruftex** [Oksydan/falcon#202]
### Description

The configuration, add new slider, of is_imageslider seems unusable in multi store and multi language context.

![Screenshot_20230316_103751-is_imageslider-bug](https://user-images.githubusercontent.com/2668191/225468921-d59c8d55-86b3-4678-b4c8-bf74b62c2c66.png)

### Node.js version

n/a

### php version

8.1.2-1ubuntu2.11

### OS and it's version

Ubuntu 22.04

### Browsers

Chrome

### Required module/theme

is_imageslider

### Reproduction steps

```bash
Environment:
is_imageslider 2.0.1 and the other modules for the falcon theme
multi store enabled with two shops on separate domains
multi language with two languages, de and en

In context "All shops" I call configure and add new slider. I upload an image, however, there is no feedback, the field says still "Choose file(s)". But on mouse over the image file is displayed.

Also there are select boxes for de and en, I cannot select another language then en.

When I hit save, without adding more data, I get multiple errors, that the language variants are missing. See above. 

Expectations:
- I can switch to the other language and enter data
- Entering the default language is sufficient

Hint: The original ps_imageslider requires to select a specific shop. When calling configure in the "All Shops" context, it says: You cannot manage slides items from a "All Shops" or a "Group Shop" context, select directly the shop you want to edit

When I select one shop context with is_imageslider I have the same problem as described above.

Unfortunately, I don't have time to make a better bug report and state the steps to reproduce with a fresh installation. Hope this is helpful for the moment.
```

**Comment by Oksydan** [comment]
HI @cruftex,

thank you for creating an issue.
I was able to reproduce an issue.
I am aware of it and I will try to fix it ASAP.

**Comment by Oksydan** [comment]
Hi @cruftex,

new version has been released https://github.com/Oksydan/is_imageslider/releases/tag/v2.1.0 and multilang problem should be solved.
Unfortunately I wasn't able to reproduce that problem with "All shop" context or Group context.
Did you enabled multistore feature before or after module has been installed?

**Comment by Oksydan** [comment]
Hi @cruftex,

I did some research and I was able to reproduce an problem with that shop group/all shop context.
It's actually related to prestashop core and I will create an issue to prestashop project. 
We can close this issue coz it's not related to module itself.
