### ISSUE TITLE
🐛 [BUG] - ContextErrorException

### ISSUE THREAD

**Issue by develobora** [Oksydan/falcon#203]
### Description

"Trying to get property 'nodeValue' of non-object, `HtmlOutput.php:27`. 

Method `hookActionOutputHTMLBefore()`, need to replace: 

```
$rel = $link->attributes->getNamedItem('rel')->nodeValue;
```
to 
```
$rel = $link->hasAttribute('rel') ? $link->attributes->getNamedItem('rel')->nodeValue : false;
```

![image](https://user-images.githubusercontent.com/25381857/225861706-c3f5e515-bf02-4573-89ac-8135eb31b5ae.png)

### Node.js version

v14.17.3

### php version

v7.4

### OS and it's version

Ubuntu 22.04! :D 

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to 'Product page'
```

**Comment by Oksydan** [comment]
Hi @develobora,

new version has been released and this issue has been fixed.
Thank you for creating an issue.
