### ISSUE TITLE
🐛 [BUG] - WEBP problem with generation images with parameter in extension

### ISSUE THREAD

**Issue by develobora** [Oksydan/falcon#204]
### Description

Images in WEBP format are not generated for photos that have a parameter in the extension ex. "xyz.jpg?t=1234".

Quick fix:
`WebpPictureGenerator.php:81`, method `generatePictureTagFromImg()`

```
if (!in_array($imageSrc['ext'], $this->allowedExtensions)) {
    continue;
}
```
replace with

```
$ext = explode('?', $imageSrc['ext']);
if (!in_array($ext[0], $this->allowedExtensions)) {
    continue;
}
```

Not sure if it's correct solution, but for now - works. 

### Node.js version

v14.17.3

### php version

v7.4

### OS and it's version

Ubuntu 22.04! :D 

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to 'is_themecore'
2. Click on 'enable webp'
3. Scroll down to 'any images on page'
4. See image property
5. See error
```

**Comment by Oksydan** [comment]
Hi @develobora,

new version has been released and this issue has been fixed.
Thank you for creating an issue.
