### ISSUE TITLE
🚀 [REQUEST] - is_themecore how to add custom elements in presentedStructuredData

### ISSUE THREAD

**Issue by Kandax86** [Oksydan/falcon#205]
### Summary

Hi, 
i have to add custom elements in the structured data generated by is_themecore. Is there a way to add some custom entries in for exemple : 
in StructuredDataWebsitePresenter
```
private function presentShopData(): void
    {
        $this->presentedData['@context'] = 'http://schema.org';
        $this->presentedData['@type'] = 'WebSite';
        $this->presentedData['url'] = $this->context->link->getPageLink('index');
        $this->presentedData['image'] = [
            '@type' => 'ImageObject',
            'url' => $this->websiteData['logo'],
        ];
    }
```
by a hook or i have to override  getStructuredData function in Header hook?
Thanks in advance for your help

### Feature target required module/theme

is_themecore

### Drawbacks

NA

**Comment by Oksydan** [comment]
Hi @Kandax86,

actually there is hook to modify structured data only for product data `actionStructuredDataProductProvider`.
I think adding dynamic hook for every structured data might be good addition.

**Comment by Kandax86** [comment]
Thank you for your answer 
actually a hook for each type of structure is a great idea. I'll add it on my project by hacking the core while we add this functionnality on each types.

**Comment by Kandax86** [comment]
hi in fact your hook doesn't modify the structured data but the product data itself. There is no way to modify $this->presentedData before the template fetch and json_encode of this $this->presentedData array.
Can you help me with this?

**Comment by Kandax86** [comment]
actually i added a hook "actionStructuredDataWebsitePresenter" StructuredDataWebsitePresenter. I think it can be interrested to add this in order to modify the data.

```
public function present($websiteData): array
    {
        $this->websiteData = $websiteData;

        $this->presentShopData();
	
		\Hook::exec('actionStructuredDataWebsitePresenter',
			[
				'object'=>$this->websiteData,
				'data' => &$this->presentedData
			]
        );

        return $this->presentedData;
    }
```

**Comment by Oksydan** [comment]
Hi @Kandax86,

I just merged to develop branch changes that allow you modify every key/value of structured data or append new one via hooks https://github.com/Oksydan/is_themecore/pull/40

**Comment by Oksydan** [comment]
Hi @Kandax86,

new version has been released, you can read how to use hooks [here](https://github.com/Oksydan/is_themecore#structured-data-modification)

I am closing this issue, thank you ❤️
