### ISSUE TITLE
Cannot install module is_themecore. The module is invalid and cannot be loaded.

### ISSUE THREAD

**Issue by aponahamed** [Oksydan/falcon#207]
### Description

When i try to install falcon theme in my Prestashop back office. showing this error

### Node.js version

18.15.0

### php version

7.4.29

### OS and it's version

windows 10 - Ram 4

### Browsers

Chrome

### Required module/theme

is_themecore

### Reproduction steps

```bash
1. download falcon theme 
2. placed theme file in Prestashop backend theme folder
3. when try to active theme show error
4. See error
```

**Comment by aponahamed** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/48320892/228629990-546d4e8b-6178-47bb-b422-4686d54188c4.png)

**Comment by Oksydan** [comment]
hi @aponahamed,

looks like you didn't read installation instruction.
Please go to instruction and follow every step of installation. 
https://github.com/Oksydan/falcon#installation 

Please be aware of this issue https://github.com/Oksydan/falcon/issues/206. I am fixing it ATM but better use older version of is_imageslider module.

**Comment by Oksydan** [comment]
New version of slider has been released https://github.com/Oksydan/is_imageslider/releases/tag/v2.1.1 you can ignore that message about about is_imageslider module.

**Comment by Oksydan** [comment]
Hi @aponahamed,

since there was no news from you in 2 weeks I am going to close this issue.
Feel free to open new one if you still need help.
