### ISSUE TITLE
is_image_slider on add slide : Argument #1 ($shopId) must be of type int, string given

### ISSUE THREAD

**Issue by rflorent** [Oksydan/falcon#208]
### Description

Hi,

When adding a new slide : 

`PrestaShop\PrestaShop\Core\Domain\Shop\ValueObject\ShopConstraint::shop(): Argument #1 ($shopId) must be of type int, string given, called in /Users/florent/Sites/top-dropship/httpdocs/modules/is_imageslider/src/Cache/TemplateCache.php on line 125`

==> ShopConstraint::shop('1')

`TemplateCache->setCacheValidityDateForSlider() in[ modules/is_imageslider/src/Cache/TemplateCache.php ](line 69)`

==> id need to be converted in real integer, maybe use intval()

`$shopConstraint = ShopConstraint::shop($store['id_shop']);`

==> `$shopConstraint = ShopConstraint::shop((int) $store['id_shop']);`

### Node.js version

v16

### php version

8.0.2

### OS and it's version

MacOs

### Browsers

Firefox

### Required module/theme

is_imageslider

### Reproduction steps

```bash
1. Go to module is_imageslider
2. Click on add slide
3. fill the form and submit
4. See error
```

**Comment by Oksydan** [comment]
HI @rflorent,

thank your for creating an issue and contribution :)

**Comment by Oksydan** [comment]
Hi @rflorent,

new version has been released https://github.com/Oksydan/is_imageslider/releases/tag/v2.1.2 
I am closing this issue.

Thank you again for your work ❤️
