### ISSUE TITLE
🐛 [BUG] - Release 3.0.2 does not contain falcon subdirectory

### ISSUE THREAD

**Issue by cruftex** [Oksydan/falcon#210]
### Description

The latest release does not contain the `falcon` subdirectory in the zip file. This differs from 3.0.1 zip file which includes the theme files in the single `falcon` subdirectory. Intentional or mistake?

### Node.js version

n/a

### php version

n/a

### OS and it's version

n/a

### Required module/theme

n/a

### Reproduction steps

```bash
unzip falcon.zip
```

**Comment by Oksydan** [comment]
Hi @cruftex,

yes it was on purpose. 
Actually it's proper folder structure to upload theme via BO. 

I was thinking about creating github action to make releases automatic. It should simplify releases and reduce possibility to make dumb mistakes while releasing (I had few 😂)
