### ISSUE TITLE
🐛 [BUG] - Customer service / contact-us form no user feedback when file is attached

### ISSUE THREAD

**Issue by cruftex** [Oksydan/falcon#211]
### Description

After the user chooses a file, the form still shows "Choose file"

### Node.js version

n/a

### php version

8.1

### OS and it's version

Ubuntu 22.04

### Browsers

Chrome

### Required module/theme

falcon

### Reproduction steps

```bash
1. Go to /contact-us
2. Click 'Browse' and select a file
3. Form still shows 'Choose file'
```

**Comment by Oksydan** [comment]
HI @cruftex,

it's really good idea.
I will implement this in version 3.1.0 that should be 'soon' ready.

**Comment by cruftex** [comment]
@Oksydan the original template does display the filename after attachment.

Do you have any plans to do automated UI testing?

**Comment by Oksydan** [comment]
Hi @cruftex,

I would love to automate some stuff like UI testing but I don't have enough time unfortunately.
If you would like to do it or you know someone who is willing to do feel free to contribute.

**Comment by Oksydan** [comment]
Hi @cruftex,

new version has been released and this issue has been resolved. 
I am closing it. 

Thank you for contribution ❤️
