### ISSUE TITLE
🐛 [BUG] - Use the SemVer notation inside compatibility settings

### ISSUE THREAD

**Issue by PrestaEdit** [Oksydan/falcon#220]
### Description

Regarding the SemVer notation, PrestaShop 8 is named 8.0.0 and doesn't have four digits possible.

### Node.js version

n/d

### php version

n/d

### OS and it's version

n/d

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to settings file
2. See the version
```

**Comment by Oksydan** [comment]
Hi @PrestaEdit,

new version has been released and this issue right now can be closed.

Thank you for your contribution ❤️
