### ISSUE TITLE
🚀 [REQUEST] - [is_favoriteproducts] Module for Falcon 2.X.X

### ISSUE THREAD

**Issue by augustomurri** [Oksydan/falcon#232]
### Summary

Where i can download module is_favoriteproducts 1.X.X for Falcon 2.X.X
I tried to download and install this [https://github.com/Oksydan/is_favoriteproducts/releases/download/v1.0.0/is_favoriteproducts.zip](https://github.com/Oksydan/is_favoriteproducts/releases/download/v1.0.0/is_favoriteproducts.zip) on PS1.7.8.8 but is not compatible  (min: 8.0.0)

thanks

### Feature target required module/theme

is_favoriteproducts

### Drawbacks

.

**Comment by Oksydan** [comment]
Hi @augustomurri,

actually you can't. 
I did huge mistake in docs support table 🤯 there is only version 1.0.0 for now.
It only works for prestashop 8.0 and falcon theme >= 3.1.0.

**Comment by Oksydan** [comment]
Hi @augustomurri 

new version has been released. I am closing this issue.
Thank your for your contribution.
