### ISSUE TITLE
🐛 [BUG] - Issue with "ajax" and "ajaxSearch" Call and Cart Functionality

### ISSUE THREAD

**Issue by Agnax** [Oksydan/falcon#238]
### Description

Prestashop 8.0.4
Theme 3.1.0 (I also tried with 3.1.1)
is_shoppingcart 3.0.0
is_themecore 4.1.0
is_searchbar 3.0.0

I have a problem, and it seems to be happening only to me with this issue.

The "ajax" call is not working, at least not when I perform a search. It doesn't give me a preview with the search results, and the cart doesn't update when I add a product to it.

Here are some examples:

![austromex search](https://github.com/Oksydan/falcon/assets/29905447/af35888f-d2f2-4868-84f7-19a9ca938ff9)

![austromex cart](https://github.com/Oksydan/falcon/assets/29905447/0b48a511-8e65-446d-967d-24992323072d)

Things I have already done:

- I performed a clean reinstallation of PrestaShop.
- I performed a clean reinstallation of the theme without my modifications.
- I ensured that the required module settings are properly configured.

Is there anything I missed configuring? The environment where I'm testing this is Cpanel Apache Version 2.4.57.

I don't know if this is useful but when I enter the following address I get the following message:

**[shop_url]/module/is_shoppingcart/ajax**
![image](https://github.com/Oksydan/falcon/assets/29905447/7b359dc3-ee7e-491e-a7ea-8fbce6315fd8)

Considering that if I directly access your demo using the same path and something else comes up, I don't know what to think.

![image](https://github.com/Oksydan/falcon/assets/29905447/61ef92ca-b0e6-4c20-9ebd-b5660735bbc9)

But if I make a query directly, it works.

![image](https://github.com/Oksydan/falcon/assets/29905447/035f2286-7ba5-40b8-85e0-2ecc9f9dfe07)

### Node.js version

v16.13.0

### php version

v7.4

### OS and it's version

Linux (x86_x64) idk what distro it is

### Browsers

Microsoft Edge

### Required module/theme

is_shoppingcart and is_searchbar

### Reproduction steps

```bash
1. Add a product to the shopping cart.
2. It won't do anything.
3. Refresh the page, and the cart will have the new information.
```

**Comment by pibrom** [comment]
Hello,
I'm having a similar problem with AJAX calls.
Once the theme is installed V 3.1.1 via the ZIP archive in release, everything works fine, Ajax calls (search, add to cart) work as expected.
But once the assets folder has been recompiled via webpack, the Ajax calls no longer display the modal windows (product search or add-to-cart confirmation modal).
My Node parameters, hosting, etc. are the same.

**Comment by Oksydan** [comment]
Hi @Agnax, @pibrom,

looks like your files are missing module code. 
Can you tell me how did you build your assets and what package manager and version are you using? (yarn/npm/pnpm)

Yes that url will return you that error it should contain `exit` if there is no ajax used. Actually we are using this controller only for that ajax request.

**Comment by pibrom** [comment]
Hello @Oksydan 
I used npm to build my assets, my version is : 9.7.1
I used only the command npm run watch to build.

**Comment by Oksydan** [comment]
Hi,

I tried to reproduce an issue with node version `18.12.1` and npm version `18.12.1` but everything is working as expected 😕. 
It just looks like you are missing that modules assets. It should compile those files and include them in theme.js files. 
```
modules by path ../../../modules/ 15.9 KiB (javascript) 580 bytes (css/mini-extract)
  modules by path ../../../modules/is_favoriteproducts/_theme_dev/src/ 7.72 KiB (javascript) 580 bytes (css/mini-extract) 6 modules
  modules by path ../../../modules/is_searchbar/_theme_dev/src/js/theme/ 3.92 KiB 2 modules
  ../../../modules/is_shoppingcart/_theme_dev/src/js/theme/index.js 2.81 KiB [built] [code generated]
  ../../../modules/is_themecore/_theme_dev/src/js/listing/index.js 1.42 KiB [built] [code generated]
```

Could you check if for example `rootProject/modules/is_searchbar/_theme_dev/src/js/theme/index.js` file exists in your project? 
BTW I recommend using dev script instead of watch script for development. Watch script won't load your changes live with HMR.  
I am not sure if your problem is windows specific problem 🤔. Are you using windows WSL? 
You can also add check what extraEntries your webpack config is trying to add. Go to `themes/falcon/_dev/webpack/webpack.vars.js`, find:

```js
      const extraEntries = [];

      for (const workspace of workspaces) {
        extraEntries.push(...glob.sync(`${workspace}/src/js/${entry}/index.js`));
        extraEntries.push(...glob.sync(`${workspace}/src/css/${entry}/index.scss`));
      }
```

and add after that `for of`:
```js
console.log(extraEntries);
process.exit(0);
````
Then run `npm run build` and check output in your terminal. 

It should contains a least:
```
  '../../../modules/is_searchbar/_theme_dev/src/js/theme/index.js',
  '../../../modules/is_shoppingcart/_theme_dev/src/js/theme/index.js',
```
If you are using `is_favoriteproducts` module is should log:

```
  '../../../modules/is_favoriteproducts/_theme_dev/src/js/theme/index.js',
  '../../../modules/is_searchbar/_theme_dev/src/js/theme/index.js',
  '../../../modules/is_shoppingcart/_theme_dev/src/js/theme/index.js',
  '../../../modules/is_favoriteproducts/_theme_dev/src/css/theme/index.scss'
```

**Comment by Agnax** [comment]
Apologies for the delay, I was running some tests because I didn't know about adding modules to the project folder. Thank you so much for your patience with all my questions.

Unfortunately, when I followed your instructions to add:

```
console.log(extraEntries);
process.exit(0);
```
It only displays an empty array.
I also installed the same version of Node and updated npm.

Should I update something else?

I'm not using Windows WSL, but after this comment, I'll install it to see if it works. If not, I'll also try using a Live USB with Linux to see if it works.

What else could be causing my array to be empty?

![image](https://github.com/Oksydan/falcon/assets/29905447/a9af18c7-7fab-4a2b-a8f4-ad75cdac6779)

**Comment by Agnax** [comment]
Solved!

![image](https://github.com/Oksydan/falcon/assets/29905447/b224e86c-d2ef-4125-9dcf-7b435e97b2a7)

I have solved the problem. The issue was in the package.json file under the WorkSpaces section.

During these days without a response, I have been investigating (although I also attended to other unrelated matters, hence the delay).
But basically, my modules are not located at "../../../modules/*/_theme_dev/"

Instead, they are located at: "../modules/*/_theme_dev/" in relation to the package.json file.

Here is my folder structure:
├── assets
│   ├── css
│   ├── fonts
│   ├── img
│   ├── img-dist
│   ├── js
│   └── preload.html
├── cache
├── config
│   ├── assets.yml
│   └── theme.yml
├── _dev
│   ├── css
│   ├── img
│   ├── js
│   ├── node_modules
**│   ├── package.json** <-------- 
│   ├── package-lock.json
│   ├── webpack
│   ├── webpack.config.js
│   └── yarn.lock
├── falcon.zip
├── LICENSE.md
├── Makefile
\├── modules
│   ├── blockreassurance
│   ├── contactform
**│   ├── is_imageslider
│   ├── is_searchbar
│   ├── is_shoppingcart
│   ├── is_themecore**
│   ├── productcomments
│   ├── ps_advertising
│   ├── ps_banner
│   ├── ps_bestsellers
│   ├── ps_brandlist
│   ├── ps_categoryproducts
│   ├── ps_categorytree
│   ├── ps_contactinfo
│   ├── ps_crossselling
│   ├── ps_currencyselector
│   ├── ps_customeraccountlinks
│   ├── ps_customersignin
│   ├── ps_emailalerts
│   ├── ps_emailsubscription
│   ├── ps_facetedsearch
│   ├── ps_featuredproducts
│   ├── psgdpr
│   ├── ps_imageslider
│   ├── ps_languageselector
│   ├── ps_legalcompliance
│   ├── ps_linklist
│   ├── ps_mainmenu
│   ├── ps_newproducts
│   ├── ps_productinfo
│   ├── ps_rssfeed
│   ├── ps_sharebuttons
│   ├── ps_socialfollow
│   ├── ps_specials
│   ├── ps_supplierlist
│   └── ps_viewedproduct
├── package-lock.json
├── preview.png
├── README.md
└── templates
    ├── catalog
    ├── checkout
    ├── cms
    ├── components
    ├── contact.tpl
    ├── customer
    ├── errors
    ├── index.tpl
    ├── layouts
    ├── page.tpl
    └── _partials
    
It's most likely that I made a mistake at some point. I apologize for that. However, if anyone else encounters the same issue, I recommend verifying if the modules are being added to the correct folder.

Thank you for your patience and sorry for the inconvenience!

**Comment by pibrom** [comment]
Thanks for thé solution !
I'm on vacations these 2 following weeks, so I'll try this solution when I get back to work.

**Comment by Oksydan** [comment]
HI @pibrom @Agnax,

that's not proper solution.
You modules should stay inside root/modules folder. Not inside theme folder. 
```
../../../modules
``` 
should take you up to root modules folder and there your js/css source files should exists. 

Unfortunately I wasn't able to reproduce an issue. In fact I have no idea how to reproduce it. If you are inside `themes/theme_name/_dev` that `../../../` should take you up to root folder.

**Comment by Agnax** [comment]
I know it's not an appropriate solution, but now that you mention it, it's most likely that those who experience this issue don't have PrestaShop installed locally, only the theme like in my case.

Honestly, I was a bit lazy to do a local installation, I just wanted to work with the theme. However, I also don't want to work improperly, so I will install PrestaShop locally. That will most likely solve the original problem.

Once again, thank you very much for your patience, @Oksydan.
