### ISSUE TITLE
Button add a specific amount to the basket

### ISSUE THREAD

**Issue by zafon18** [Oksydan/falcon#239]
### Summary

Prestashop - 8.1.0
PHP - 8.2
Falcon - 3.1.1

Hi,
Many thanks for your work on the theme. Good job!
I wanted to add a button with a certain number of products on the product thumbnail. I modified the product-form.tpl file with the code.
/themes/falcon/templates/catalog/_partials/miniatures/_partials/product-form.tpl

`<div class="qty col-12 col-sm-auto mx-auto mt-2 px-1">
             <input
               type="number"
               name="qty"
               id="quantity_wanted"
               inputmode="numeric"
               pattern="[0-9]*"
               {if $product.quantity_wanted}
                 value="{$product.quantity_wanted}"
                 min="{$product.minimal_quantity}"
               {other}
                 value="1"
                 minutes="1"
               {/if}
               class="input-group input-touchspin"
               aria-label="{l s='Quantity' d='Shop.Theme.Actions'}"
             />
</div>`

The code works, but only for the first product, nothing appears in the others. Do you have an idea how to modify the code so that it works on all products in the listing?
Additionally, is there a bulk button that will allow you to add the quantities entered on the thumbnails to the cart?
Thanks for the help.
![miniatures](https://github.com/Oksydan/falcon/assets/46523554/e9b1c2aa-b86f-427c-9308-a4f571f804a8)

### Feature target required module/theme

Falcon

### Drawbacks

None

**Comment by Oksydan** [comment]
Hi @zafon18,

don't add one id `quantity_wanted` to input, id have to be unique. Thb you don't need id at all. 
If your remove that id you will have to initialize touchspin by yourself and you should checkout cart.js or product.js for some hints how it's working with touchspin.
Bulky add to cart isn't part of prestashop core. It's required to create an module or add some extra logic and endpoint to existing prestashop core.

**Comment by Oksydan** [comment]
Hi @zafon18,

since you didn't response in more than 3 weeks. 
I am closing this issue. Feel free to open new one.
