### ISSUE TITLE
🐛 [BUG] - is_imageslider highest position

### ISSUE THREAD

**Issue by rflorent** [Oksydan/falcon#246]
### Description

Hello,

I think there is a bug with this repository method, we want the highest position not the lower position.
`orderBy('s.position', 'ASC')` should be `orderBy('s.position', 'DESC')`.

`
public function getHighestPosition(): int
    {
        $position = 0;
        $qb = $this
            ->createQueryBuilder('s')
            ->select('s.position')
            ->orderBy('s.position', 'ASC')
            ->setMaxResults(1)
            ->getQuery();

        $result = $qb->getOneOrNullResult();

        if ($result) {
            $position = $result['position'];
        }

        return $position;
    }
`

### Node.js version

v16

### php version

8.0.2

### OS and it's version

Mac osx

### Required module/theme

is_imageslider

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

**Comment by Oksydan** [comment]
HI @rflorent,

Thank you for creating an issue. Yes, you are right.
It's actually minor bug and I will fix it in next version.

**Comment by Oksydan** [comment]
Hi @rflorent ,

new version has been released. Thank you for your contribution.
