### ISSUE TITLE
🐛 [BUG] - Modules search bar - shopping cart - don't use the new translation system

### ISSUE THREAD

**Issue by rflorent** [Oksydan/falcon#247]
### Description

Translations are not shown in admin because modules don't use the new translation system.
Add the following to the main module's class : 

`    public function isUsingNewTranslationSystem()
    {
        return true;
    }
    `

### Node.js version

V14

### php version

8.1

### OS and it's version

MacOs X

### Required module/theme

is_shoppingcart, is_searchbar

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

**Comment by Oksydan** [comment]
Hi @rflorent,

thank you for creating an issue. 
You are right about wrong domains for modules. 
In version 3 we removed every theme override for those templates and moved from theme directory to module directory. 
I didn't pay attention to those translation domains and it should be fixed.

**Comment by rflorent** [comment]
HI @Oksydan,

Thanks.

`isUsingNewTranslationSystem`is also missing.
Without it, translations that use domain (d='xxx') aren't shown in admin.
Old translation system is used instead (mod='mymodule')

**Comment by Oksydan** [comment]
Hi @rflorent,

new version has been released.
I am closing this issue.
