### ISSUE TITLE
🐛 [BUG] - Problem to remove products from cart block when there is a different combination from default

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#249]
### Description

Hi
found a new bug
it is a javascript error and it happens when it is selected a product with combinations, but it is added a combination other than the default one

![1](https://github.com/Oksydan/falcon/assets/653230/7ab78ac1-3f82-4750-8645-8a319f2919cc)

bye

### Node.js version

v16.20

### php version

8.1

### OS and it's version

linux

### Required module/theme

theme

### Reproduction steps

```bash
look at this video

https://watch.screencastify.com/v/CM1yfmRWU8ERHkSxZsUC

go in the product page of a product with combinations and select the not default one, then try to remove it from the cart block
```

**Comment by Oksydan** [comment]
Hi @maofree,

unfortunately I wasn't able to reproduce an issue.
Could you show me what function is causing this problem. 
This stack trace is not telling me anything.

**Comment by maofree** [comment]
it is a bug of prestashop 8.1
https://github.com/PrestaShop/PrestaShop/issues/33473

bye
