### ISSUE TITLE
🐛 [BUG] [FIXED] - in the products list the stars of module productcomments are not shown if the is the updatedProductList event in the page

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#252]
### Description

Hi

it is necessary to set this code in the file modules/views/js/productListingComments.js

`$(document).ready(function() {
    productListingComments.init();
    productListingComments.load();
    
    if (typeof prestashop !== 'undefined') {
        prestashop.on("updatedProductList", () => {
            productListingComments.init();
            productListingComments.load();
        });
    }
});`

if not if there is some change into the page, the stars will be shown

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

productcomments

### Reproduction steps

```bash
1. Add a comment to a product
2. go in its category page and see its stars
3. do something like pass from grid to list view or select an attribute from the filter
4. now the stars are no more present in the miniature
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue and providing solution to fix the problem.
