### ISSUE TITLE
🐛 [BUG] [FIXED] - productcomments have a javascript conflict in the product pages

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#253]
### Description

Hi
I've found a javascript conflict inside from list-comments.js and productListingComments.js in the product pages

if there is at least a carousel like the ps_categoryproducts or similar and the current product has one or more comments, the stars of the products inside the carousel will be all to 1 star.
If I remove all code of list-comments.js the stars inside the block carousel are ok

I show you with and without list-comments.js code
![2](https://github.com/Oksydan/falcon/assets/653230/b1aa8aa9-1dd7-4110-ad47-3721cc1080be)
![1](https://github.com/Oksydan/falcon/assets/653230/9dc668bc-bbb8-451d-ba40-2b579f6dbbe3)

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

productcomments

### Reproduction steps

```bash
1. Add a comment to two products of the same category
2. go to the product page of one product and go down to see the second product inside the carousel of ps_categoryproducts module
3. you can see the second product (inside the carousel) will have just one star
4. instead in the homepage, category pages ... the stars are ok, this problem is only in the product page

Now I've seen that the problem is present also in product page without comments, because it is loaded the file list-comments.js
```

**Comment by maofree** [comment]
I've fixed the problem inside list-comments.js file

replace the two lines

`$('.grade-stars').rating();`

with

`$('.comments-note .grade-stars').rating();`

**Comment by maofree** [comment]
Hi
I've found some little errors in the post-comment-modal.tpl file
the for attributes should be removed because they refer to the name attributes and not to the ID ones

for="comment_title"
for="customer_name"
for="comment_title"
for="comment_content"

![1](https://github.com/Oksydan/falcon/assets/653230/d4801a84-2b52-4f9a-88e8-805dd7134515)
![2](https://github.com/Oksydan/falcon/assets/653230/3c3e0564-5c13-48e3-b943-992fb6a9712c)

I report the error also to those of prestashop

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue and providing solution.

**Comment by Oksydan** [comment]
Hi @maofree,

new version has been released. I am closing this issue.
Thank your for your contribution.
