### ISSUE TITLE
🐛 [BUG] - Found 2 errors on the is_imageslider module

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#255]
### Description

Hi
Found 2 errors on the is_imageslider module:

1) the module does not consider the possibility that the site is inserted in one or more folders, it is necessary to add a reference to the webroot of the site if this is inserted in a folder such as /shop/
This problem is present in the front-office and in the back-office with the preview images

2) the name of the image is causal like this bc57fe814ca7a0e9020d99877cf45fb2.webp this solution is not correct on the seo side. I think it's better if it has the same name as the inserted image

![1](https://github.com/Oksydan/falcon/assets/653230/30d8cb85-dbbb-42ae-a14a-3d71ebaa1fb1)
![2](https://github.com/Oksydan/falcon/assets/653230/02d13745-4733-497a-8e96-573910c649ec)

for the moment I've fixed this problem editing this line inside ImageSlidePresenter.php
`return $this->context->link->getMediaLink(_MODULE_DIR_.'..'.$this->imagesUri . $slideImage);`

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

is_imageslider

### Reproduction steps

```bash
1. create a folder named "shop" or like you want, install prestashop and theme inside it
2. add an image to is_imageslider
3. the image will not shown in the preview images and in the front-office
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue. 
We are hashing name with timestamp to make sure there is no samename filename conflict. 
For SEO side it's all about proper alt name instead of filename tbh. We can stick to original filename by we have to add random hash to it to prevent files name conflicts.

**Comment by Oksydan** [comment]
Hi @maofree,

new version has been released. Thank you for your contribution.
