### ISSUE TITLE
🐛 [BUG] - add required social icons for ps_socialfollow module

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#257]
### Summary

Hi
is it possible to add extra icons to icomoon ?
- telegram
- messenger
- whatsapp
- tiktok
- evenlop

and others managed by the ps_socialfollow module

### Feature target required module/theme

theme

### Drawbacks

I think it should be useful

bye

**Comment by maofree** [comment]
I figured out how to add more icomoon icons to the already present ones, by reading README.md
however it might be useful to add them by default

**Comment by Oksydan** [comment]
Hi @maofree,

we can add icons required by `ps_socialfollow` module to cover all socials icons. 
I not sure about adding extra icon like `envelope`  since we are using material icons this kind of icon is currently available.

**Comment by Oksydan** [comment]
Hi @maofree,

i am transition this feature request to bug report.
If prestashop native module requires from us to use tiktok, rss, discord icons we have to provide it. 
Nothing more than that will be added to Falcon core. 
If your need more icons in your project you can simply add more via icomoon app.

**Comment by maofree** [comment]
Hi
they are also useful for whatsapp, telegram and messenger

**Comment by Oksydan** [comment]
Hi @maofree 

new version has been released. I am closing this issue.
Thank your for your contribution.
