### ISSUE TITLE
🐛 [BUG] - ps_checkout doesn't work

### ISSUE THREAD

**Issue by cdigruttola** [Oksydan/falcon#260]
### Description

Using the ps_checkout module for payment, the js try to search for div with id like this 
`id="{$option.id}-container"`
but in the theme is missing

### Node.js version

v16.18.1

### php version

v8.1

### OS and it's version

MacOS Ventura

### Required module/theme

theme

### Reproduction steps

```bash
Install and configure ps_checkout
Go in Checkout page
See error in console
```

**Comment by Oksydan** [comment]
Hi @cdigruttola,

Thank you for creating an issue and for PR 😍

**Comment by Oksydan** [comment]
Hi @cdigruttola,

new version has been released. I am closing this issue.
Thank your for your contribution.
