### ISSUE TITLE
🐛 [BUG] - Uncaught TypeError: Cannot read properties of null (reading 'closest') - checkout page

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#261]
### Description

Hi
in the checkout page I see this little javascript error

![1](https://github.com/Oksydan/falcon/assets/653230/b2d192d1-86df-49a5-be61-9e6acfea358b)

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Add a product in the cart
2. go to the checkout and see in the console log
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue. 
I was able to reproduce an issue.

**Comment by Oksydan** [comment]
Hi @maofree,

new version of `is_searchbar` module has been released https://github.com/Oksydan/is_searchbar/releases/tag/v3.0.1
I can close now this issue. 
Thank your for creating an issue.

**Comment by maofree** [comment]
thanks

**Comment by maofree** [comment]
sorry but I get the same problem
I think the problem in into theme.js, because it doesn't see the that class .js-search-form
the header section is just with the logo

**Comment by Oksydan** [comment]
Hi @maofree, 
Did you build your theme after adding mousier in newer version? We are using Workspaces Aware Webpack in is_searchbar module.

**Comment by maofree** [comment]
Hi
no I didn't
ok understood
