### ISSUE TITLE
🐛 [BUG] - issue of misalignment of entries in customer account

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#262]
### Description

Hi
issue of misalignment of entries in customer account
entries are hidden for devices with small widths

![1](https://github.com/Oksydan/falcon/assets/653230/f66e540a-9324-44f3-8f95-f0c00e0a58ad)
![2](https://github.com/Oksydan/falcon/assets/653230/d2435145-48ca-41bf-bdec-91095bbf3e01)

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Login with a customer account
2. go into its page
3. reduce the width of the page
4. the voices will go outside from the view
```

**Comment by Oksydan** [comment]
Hi @maofree,

it's not a bug. Those elements are scrollable you can scroll right to display other elements. I know that's not the best UX but in version 4 we will rebuild it . There will be side drawer with account links.
