### ISSUE TITLE
🐛 [BUG] - Automatically cart rules not applied

### ISSUE THREAD

**Issue by futurowebpl** [Oksydan/falcon#263]
### Description

Hi,

I do not know if it is related to Falcon, but on 2 instances of Falcon, automatically added cart rules do not work (they only work if a discount code is provided - while without the code - automatically assigned rules do not work).

Could some kind soul check if the automatic rules of the cart work in Falcon (e.g. free product) without the discount code.

Prestashop 8.1.1
Falcon v3.1.1

### Node.js version

v14.1.0

### php version

v8.1

### OS and it's version

MacOS

### Browsers

Firefox

### Required module/theme

is_shoppingcart

### Reproduction steps

```bash
1. Go to 'Cart Rules'
2. Add new 'Cart Rule' without Voucher Code eg. automatically gift product for all
3. Check Shopping Cart
4. See if contain free gift product
```

**Comment by Oksydan** [comment]
Hi @futurowebpl,

Falcon theme and it's modules don't touch Cart logic at all. 
There is no way Falcon theme might cause this kind of issue. 
Whole logic for applying automatic CartRules to cart you can find in Cart.php class.

**Comment by futurowebpl** [comment]
Okay,

I know - It sounds idiotic, but I'm looking for a starting point.

Thanks for this answer.
