### ISSUE TITLE
🐛 [BUG] - is_imageslider doesn't create ImageSliderLang in case of update

### ISSUE THREAD

**Issue by cdigruttola** [Oksydan/falcon#267]
### Description

In case of an update on a slider, if after creating it you add a new language, the field for the new language are not considered

### Node.js version

v16.18.1

### php version

v8.1

### OS and it's version

MacOS Ventura

### Required module/theme

is_imageslider

### Reproduction steps

```bash
1. Go to Image Slider configuration
2. Create a new Slider
3. Go to International and add a new language
4. Go back in slider configuration and edit the previously created slider
5. Compile fields for the new language and Save
6. Try to edit again and the fields are empty, in the DB no new row were created
```

**Comment by Oksydan** [comment]
Hi @cdigruttola,

new version has been released. Thank you for your contribution.
