### ISSUE TITLE
🐛 [BUG] - Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#268]
### Description

Hi
I've found an error on the cross button of the cart block

![1](https://github.com/Oksydan/falcon/assets/653230/13b8b2e7-c020-4712-a057-843acea71107)

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

is_shoppingcart

### Reproduction steps

```bash
1. Add a product in the cart
2. open the cart block
3. push on the cross button to close it
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue.
I was able to reproduce the problem.

**Comment by Oksydan** [comment]
Ready in develop branch of `is_shoppingcart` module (version 4.0.0). I am closing this issue. 
Thank you @maofree
