### ISSUE TITLE
🐛 [BUG] - [FIX] missing close tag in order-detail.tpl

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#275]
### Description

Hi
it is missing the close tag inside order-detail.tpl for the div container of order-infos

![1](https://github.com/Oksydan/falcon/assets/653230/c9a232f5-12f6-4251-8ef3-67afa0766b20)

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Go in the order details page and look at the footer, the footer is inside the wrapper section, because it is missing the close tag of the div of order-infos inside order-detail.tpl
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue.
Added to 4.0 roadmap.

**Comment by Oksydan** [comment]
Hi @maofree,

this problem has been fixed. 
Thank you again for creating an issue.
