### ISSUE TITLE
🐛 [BUG] - [FIX] the gdpr checkbox doesn't appear in the product comment form

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#276]
### Description

Hi

I've seen that the gdpr checkbox doesn't appear in the comment form

it is missing this code in the file post-comment-modal.tpl

`          <div class="form-group">
              {hook h='displayGDPRConsent' mod='psgdpr' id_module=$id_module}
          </div>`

also the checks have problems, it is necessary some css code to fix it

![1](https://github.com/Oksydan/falcon/assets/653230/93883ddf-90d2-49e1-a9b0-98c365d5108d)

`div[class^="gdpr_module_"] .custom-checkbox,
.gdpr_consent .custom-checkbox {
  position: relative;
}

div[class^="gdpr_module_"] .custom-checkbox input[type="checkbox"],
.gdpr_consent .custom-checkbox input[type="checkbox"] {
  position: absolute;
  width: 18px;
  height: 18px;
  margin-top: 0.25rem;
  cursor: pointer;
  opacity: 0;
}

div[class^="gdpr_module_"] .custom-checkbox input[type="checkbox"] + span,
.gdpr_consent .custom-checkbox input[type="checkbox"] + span {
  display: inline-block;
  width: 1.125rem;
  height: 1.125rem;
  margin-right: 0.5rem;
  vertical-align: middle;
  pointer-events: none;
  cursor: pointer;
  border: 1px #979797 solid;
}

div[class^="gdpr_module_"]
  .custom-checkbox
  input[type="checkbox"]
  + span
  .checkbox-checked,
.gdpr_consent .custom-checkbox input[type="checkbox"] + span .checkbox-checked {
  display: none;
  margin: -0.125rem;
  font-size: 1.25rem;
  color: #232323;
}

div[class^="gdpr_module_"]
  .custom-checkbox
  input[type="checkbox"]:checked
  + span
  .checkbox-checked,
.gdpr_consent
  .custom-checkbox
  input[type="checkbox"]:checked
  + span
  .checkbox-checked {
  display: block;
}

div[class^="gdpr_module_"] .custom-checkbox input[type="checkbox"]:focus + span,
.gdpr_consent .custom-checkbox input[type="checkbox"]:focus + span {
  border-color: #7a7a7a;
}

div[class^="gdpr_module_"] .custom-checkbox label,
.gdpr_consent .custom-checkbox label {
  text-align: left;
}`

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
install gdpr module and productcomments just to test them
```

**Comment by maofree** [comment]
I had to reset the gdpr module because it was not present in the displayGDPRConsent hook
and then go inside the module and push on save button

I've found a problem on the check

![1](https://github.com/Oksydan/falcon/assets/653230/24134aa6-2c41-4dac-9762-f7af9f80506a)

**Comment by maofree** [comment]
I've seen that in the last version, the 6.0.2 has same changes, try to look at product-comments-list.tpl

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue. 
I was able to reproduce the problem.

**Comment by Oksydan** [comment]
Hi @maofree,

problem has been fixed. Thank you for creating an issue.
