### ISSUE TITLE
🐛 [BUG] - HTML lang is not set

### ISSUE THREAD

**Issue by cdigruttola** [Oksydan/falcon#277]
### Description

The lang attribute in HTML is not set. I checked also the online demo and the problem is present.
In localhost environment the problem is not reproduced.

### Node.js version

v16.18.1

### php version

v8.1

### OS and it's version

MacOS Ventura

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to 'layout-both-column.tpl' to check the correct valorization of attribute
2. In demo Online Inspect element
3. See the missing lang attribute in HTML tag
```

**Comment by Oksydan** [comment]
Hi @cdigruttola,

I was able to reproduce an issue. 
This problem i related to `is_themecore` module and hook `hookActionOutputHTMLBefore`. 
We are passing html document there with `DOMDocument` and in this process lang attribute is being removed. 
I will fix in next version.

**Comment by cdigruttola** [comment]
Hi,
do you have a dead line for this new version? 
I tried to check the class but I cannot understand why in the $params['html'] the lang attrbute is present but when you do $doc->loadHTML('<meta http-equiv="Content-Type" content="charset=utf-8">' . $html) the attribute is missing.

**Comment by Oksydan** [comment]
Hi @cdigruttola,

new version has been released and bug has been fixed https://github.com/Oksydan/is_themecore/releases/tag/v4.1.1|
Thank you for your contribution.
