### ISSUE TITLE
🚀 [REQUEST] - Replace widgets with hooks in contact.tpl

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#281]
### Description

Hi
today I've done some fixes into contact.tpl, if you look the contact.tpl of last classic theme you will see some changes into it

instead the fixes are about the classes

must be so
<div id="left-column" class="col-12 col-md-4 col-lg-3">
<div id="right-column" class="col-12 col-md-4 col-lg-3">

this is necessary because this div has these classes
<div id="content-wrapper" class="js-content-wrapper left-column col-12 col-md-8 col-lg-9">

![1](https://github.com/Oksydan/falcon/assets/653230/257fba53-09aa-4f67-b060-1585a3f328f1)

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Install ps_contactinfo
2. go into the contact page and look the classes of left-column and content-wrapper divs
```

**Comment by Oksydan** [comment]
Hi @maofree,

I don't understand what this issue is all about?
What is missing? I am looking at classic and I don't see anything.

**Comment by maofree** [comment]
Hi
look at the contact.tpl of the classic theme on prestashop 8.1

into the zip there are two files, one is mine fixed and the other is the default file of 8.1.1 of classic theme
https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.1

![1](https://github.com/Oksydan/falcon/assets/653230/6dd48418-c25e-4248-bcef-3d97d61efb66)

bye

**Comment by Oksydan** [comment]
Hi @maofree,

main differences are hooks instead of widgets. 
Layout classes aren't important thb. We are using different breakpoints for main layout columns.
We shouldn't change anything beside those hooks. 🤔

**Comment by maofree** [comment]
Hi
there is an error about the classes used into contact.tpl of falcon theme
the correct classes should be so
"col-12 col-md-4 col-lg-3"
and not so
"col-12 col-sm-4 col-md-3"

because the content-wrapper uses these classes
"col-12 col-md-8 col-lg-9"

in fact in this file
https://github.com/Oksydan/falcon/blob/master/templates/layouts/layout-both-columns.tpl
the left column uses
`<div id="left-column" class="col-12 col-md-4 col-lg-3">`

**Comment by Oksydan** [comment]
Hi @maofree,

problem has been fixed. Thank you for creating an issue.
