### ISSUE TITLE
🐛 [BUG] - is_imageslider - the mobile images are not converted to webp

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#283]
### Description

Hi
Now I've seen that the mobile images are not converted after the upload like the big image
in fact into the is_imageslider/img there are only two webp images, one for each slide I inserted and they refer to large images, those for mobile are only in jpeg

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

is_imageslider 2.3.1

### Reproduction steps

```bash
1. Go into the module
2. insert a new slide
3. upload the big and mobile images
4. look inside the is_imageslider/img/ folder
5. will be present only one webp image
```

**Comment by cdigruttola** [comment]
Hi,

have you also visited the page in which the slider is present? The webp images will be generated when the system ask for the page (the directives are defined in the htaccess).

**Comment by maofree** [comment]
yes you are right I thought they were created when they were uploaded.
an error in this module is that when the slides are removed, all the images associated with them are not removed. This leads to being filled with images without control

Do I need to open a new ticket for this issue?

**Comment by maofree** [comment]
Hi
ok for the webp but the jpeg images can be removed when deleting a slide

**Comment by Oksydan** [comment]
Hi @maofree 

Are you sure that images aren't erased on slider delete? I can see that those files are being removed on slide delete action. 
If you are able to reproduce an issue please create an issue.
