### ISSUE TITLE
🐛 [BUG] - is_imageslider doesn't remove the jpg images uploaded when is removed a slide

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#284]
### Description

Hi
on my demo website there are 6 languages, created 2 slides for a number of images inside is_imageslider/img/ of 30
now I do the test adding a new slide with another image set for pc and mobile device, now after that there are 42 images inside is_imageslider/img/ jpeg and webp
now if I delete this slide I think to get 30 images, because I don't reload the homepage, instead there are always the same 42 images

![1](https://github.com/Oksydan/falcon/assets/653230/50b40c65-98a2-42dc-9173-69412addacc3)
![2](https://github.com/Oksydan/falcon/assets/653230/5e6c8f48-e0df-44e5-b887-7fb4eaad714a)

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

is_imageslider 2.3.1

### Reproduction steps

```bash
1. create a new slide
2. check the number of images inside img folder
3. remove the slide
4. the number of images will be the same
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue.
I was able to reproduce an issue.

**Comment by Oksydan** [comment]
Hi @maofree,

this issue has been fixed here https://github.com/Oksydan/is_imageslider/pull/48 
It will be available in the next major version.
Thank you for your contribution.
