### ISSUE TITLE
🐛 [BUG] - [FIX] wrong condition for the alt text in some tpl files

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#285]
### Description

Hi
in these files there is a wrong condizion
product-cover-thumbnails.tpl
product-images-modal.tpl

this code

`{if !empty($product.default_image.legend)}
alt="{$image.legend}" title="{$image.legend}"
{else}
alt="{$product.name}"
{/if}`

should be so

`{if !empty($image.legend)}
alt="{$image.legend}" title="{$image.legend}"
{else}
alt="{$product.name|truncate:60:'...'}"
{/if}`

the truncate is just my preference

$product.default_image.legend
shloud be
$image.legend

if not I get the alt text void for the images except the first one on the list

![1](https://github.com/Oksydan/falcon/assets/653230/addc2186-271c-4e50-9d52-87764fb4c0a6)
![2](https://github.com/Oksydan/falcon/assets/653230/8cf76a24-9b68-471f-a3e3-8e1d71c76c9b)
![4](https://github.com/Oksydan/falcon/assets/653230/eefd9fca-d5c2-4ddf-a8ca-708ad1c7c4b8)

with that fix the problem is solved

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to a product
2. add some images to it
3. check the alt text for the second and rest of images of thumbs and for the big images
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue. 
I am adding it to roadmap for version 4.0.0

**Comment by Oksydan** [comment]
Hi @maofree,

problem has been fixed and it will available in version 4. 
Thank you again for creating an issue.
