### ISSUE TITLE
🐛 [BUG] - [FIX] .custom-control of color selections need some little fixes

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#286]
### Description

Hi
this code
`.custom-control-label:after, .custom-control-label:before {
    height: 1rem;
    top: 0.25rem;
    width: 1rem;
}`

should be so

`.custom-control-label:after, .custom-control-label:before {
    height: 1.5rem;
    width: 1.5rem;
    top: 0;
}`

and the selected color should have this code
`  .product-variants
  .custom-radio-color
  .custom-control-input:checked
  ~ .custom-control-label:after {
    left: -1.4rem;
  }`

the cursor hand does not appear on the entire color icon, but only on a small part, because the dimensions are 1.5rem and not 1rem

![1](https://github.com/Oksydan/falcon/assets/653230/7a97a01e-1bec-4a8b-a9ca-fc1b4e209982)
![2](https://github.com/Oksydan/falcon/assets/653230/d8930bfe-8867-4a35-95d8-5678ecd9cd04)

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to a product and create some combinations with colors
2. move the mouse hover the color selectors
```

**Comment by Oksydan** [comment]
Hi @maofree,

I rewrote that whole component for BS5. 
Right now input should be in proper dimensions.
