### ISSUE TITLE
🐛 [BUG] - Mini shopping cart close error

### ISSUE THREAD

**Issue by tlukowski** [Oksydan/falcon#302]
### Description

When you enable shopping cart and close it by "x"

u get error:
Uncaught TypeError: t is null

I checked it on:
https://falcon-theme.dev/en/

### Node.js version

v18.18.1

### php version

8.1

### OS and it's version

Ubuntu

### Required module/theme

is_shoppingcart

### Reproduction steps

```bash
When you enable shopping cart and close it by "x"
u get error:
Uncaught TypeError: t is null

I checked it on:
https://falcon-theme.dev/en/
```

**Comment by Oksydan** [comment]
Hi @tlukowski 

Thank you for creating an issue. Unfortunately this issue is duplication of https://github.com/Oksydan/falcon/issues/268. I am closing this issue.
