### ISSUE TITLE
🐛 [BUG] - [FIX] in brand.tpl is missing webp block

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#308]
### Description

Hi
I report a fix for miniaturs/brand.tpl, it is missing the images_block block code 

`{images_block webpEnabled=$webpEnabled}`

it is also missing the img-fluid class for the img tag

I attach here fixed file
[brand.zip](https://github.com/Oksydan/falcon/files/13197464/brand.zip)

in this mode the brand images will be in webp

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to see miniaturs/brand.tpl
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue. Since right now we are working on version 4.0.0 and the way webp is working will be reworked.  I am not going to apply that changes but I want to keep this PR to fix it in new version.

**Comment by maofree** [comment]
Hi
the 4 version is very different from the 3.1.2?
I'm afraid that it will then deviate a lot from the direction it will take with hummingbird due to compatibility problems with the extra modules. I make most of the programs myself, on the sites I manage, but I also use others that aren't mine.
Today I finished making my version using 3.1.2, it's super beautiful. in 2 weeks I'll try to put it on a big site, then I'll see how it behaves and its scores and then I'll start putting it on other sites too. But I will also have to study version 4 and report the changes to this version.
I have to fix the menu (I'll use iqitmegamenu, I saw that you're also making a megamenu, I'm happy) and the translations of the theme and extra modules. I created a form to show the brand logos, if you want I can pass it to you (it has the selection of brands, with webp and lazyload, with carousel)

**Comment by Oksydan** [comment]
Hi,

yes version 4 will be like completely new way of working with prestashop themes.
You can checkout project kanban board https://github.com/users/Oksydan/projects/1/views/1 
We are going to remove whole usage of jQuery ofc with an option to include it. We are moving to bootstrap 5.3 just like HB theme. Most of the modules will have to be adapted to HB, that is, also to the Falcon theme. 
Falcon theme is getting more and more popular. Some of the most popular module developers are staring to adjust their solution to this theme.
Native prestashop modules will be rewritten to vanilla.js and bootstrap 5 and it's currently in progress https://github.com/Oksydan/falcon/pull/307
I am going to document all components and changes relative to hummingbird, classic and core.js.

**Comment by maofree** [comment]
Hi
without core.js how is it possible to manage the prestashop's event like updateCart or similar?

`prestashop.on('updateCart', function () {`

**Comment by Oksydan** [comment]
Hi @maofree,

events are triggered just like in prestashop core.js.
It's been rewritten from scratch https://github.com/Oksydan/falcon/tree/develop/_dev/js/theme/core and it will be available inside your theme and everything is typed and documented via jsdoc.
There will be even more events than in prestashop native core.js.

**Comment by maofree** [comment]
Hi
how work the new lazyload solution?
I've seen you removed the svg file into src attribute and the data-src attribute and set the real image into src. In this mode all real image are loaded from the browser

**Comment by Oksydan** [comment]
We are using native lazyload solution. It's widely supported and we don't need js library to handle it.

**Comment by maofree** [comment]
in the classic theme is present lazyload="lazy" like here
![1](https://github.com/Oksydan/falcon/assets/653230/56105d09-314b-4c54-95ae-899b737a4bd8)

but the image is loaded even if it is not visible

are you sure that it works? have you tested it?

Sorry if I insist a little, but I don't think it works, an image is loaded if it is present in the src attribute

**Comment by Oksydan** [comment]
Yes, it's working properly. You can read specification here https://html.spec.whatwg.org/multipage/urls-and-fetching.html#lazy-loading-attributes

**Comment by maofree** [comment]
ok understood how it works, thanks

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/loading

Note: In Firefox, the loading attribute must be defined before the src attribute, otherwise it has no effect

**Comment by maofree** [comment]
HI @Oksydan 
I've done the tests to compare both solutions. It is not so simple to check it from google page speed, but using gtmetrix the scores are similar, I don't think there is much difference, on google page speed perhaps the vanilla lazyload solution is a little better

on the theme under development I move directly to the native solution, I believe that on an SEO level it could be better, given that the img tag contains the original image right away

**Comment by maofree** [comment]
I'll just give you one observation.
if there were iframes like for YouTube on the page, lazyload would always be needed, perhaps also for videos

**Comment by Oksydan** [comment]
Hi @maofree 

Thank you. Actually you can use native lazy loading for iframes. About videos ofc you need to write something custom but with intersectionObserver is should an quite easy task.

**Comment by maofree** [comment]
Hi
I've tested the native lazyload adding loading="lazy" to the iframe tag but the score become 50-55
instead with vanilla lazyload is 96-98

![1](https://github.com/Oksydan/falcon/assets/653230/13ccb893-d13d-459b-a12a-16f5e30a5f20)
![2](https://github.com/Oksydan/falcon/assets/653230/5e16ab00-3800-4800-a188-a41d1667838b)

**Comment by Oksydan** [comment]
Hi

It's about different threshold between vanilla lazy load and native solution. You can read about it here https://web.dev/articles/browser-level-image-lazy-loading?hl=en#improved_data-savings_and_distance-from-viewport_thresholds

**Comment by maofree** [comment]
thanks for the infos
however with iframes I see that it loads many files remotely even with the presence of loading="lazy" and this worsens the scores. I will only use it for iframes for the rest I use the native one

**Comment by Oksydan** [comment]
Yea, use whats the best in your case. Native lazyloading providing us easy to use tools that are currently widely supported. Most of the libraries that were relaying on their own lazyloading script moved to native solution - look at swiper for example.

**Comment by maofree** [comment]
thanks for your useful infos
later I will try to participate more in the code too, not just limiting myself to reporting errors, I will do the same thing with prestashop.

**Comment by Oksydan** [comment]
Hi @maofree,

problem has been solved on develop branch with other minor changes to brand miniature. 
Thank you for your contribution.
