### ISSUE TITLE
🐛 [BUG] - [FIX] in brand image of product-details.tpl is missing the lazyload functionality

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#309]
### Description

Hi
in the product-details.tpl is missing the lazyload functionality

![1](https://github.com/Oksydan/falcon/assets/653230/827b5ecb-261e-4812-9345-74cde0528133)

the img tag for the brand image should be so

`            {images_block webpEnabled=$webpEnabled}
              <img
                src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1 1'%3E%3C/svg%3E"
                data-src="{$manufacturer_image_url}"
                class="img img-fluid manufacturer-logo lazyload"
                alt="{$product_manufacturer->name}"
                >
            {/images_block}`

in this mode the image will load only when the details section is visible

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. go to see product-details.tpl
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue. 
I will apply suggested changes in version 4. 
We are no longer are using vanilla-lazyload library. Instead we moved to native lazy load solution. 
So proposed solution isn't valid for upcoming version. I am going to fix it in next verion.
Feel free to submit PR to develop branch but remember to create your branch from develop branch.

**Comment by Oksydan** [comment]
Lazyload has been added for this image on develop branch.
I am closing this issue.
