### ISSUE TITLE
🐛 [BUG] - missing local language to the html tag

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#311]
### Description

Hi
right now I've found a strange error
it is missing the local language at the html tag
the same problem is present into the demo site of falcon theme

![1](https://github.com/Oksydan/falcon/assets/653230/83d40894-c150-46d5-955b-99dd91635193)

it should be like so
<html lang="it-IT">
instead it is only <html>

into layout-both-columns.tpl the code is correct, is the same of classic theme, but if I write dddd it is not shown in the html code

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. look at the source code of the demo site of falcon website
```

**Comment by maofree** [comment]
I'm trying to fix this problem, but this time I don't know where the problem is. any changes I make on the html and head tag are not taken into account, on the body they are.

I put the templates folder in the classic theme but it gives the same problem, I renamed that js to js-111, thinking it was a problem in javascript but nothing

![1](https://github.com/Oksydan/falcon/assets/653230/82a21036-5b06-45b1-a2f4-e64a3a056477)

**Comment by Oksydan** [comment]
Hi @maofree,

it's been fixed [here](https://github.com/Oksydan/is_themecore/releases/tag/v4.1.1). 
Just download new version of is_themecore module or apply changes on you own.

**Comment by maofree** [comment]
ok thanks

**Comment by maofree** [comment]
the 4.1.1 version has the version 4.1.0
$this->version = '4.1.0';
instead to be 4.1.1
look at the main php file
