### ISSUE TITLE
🐛 [BUG] - JS Problems with child theme

### ISSUE THREAD

**Issue by Shoprunners** [Oksydan/falcon#313]
### Description

Hi,
if you create a very simple child theme with like only the basic config file like:

```
parent: falcon
name: xzy
display_name: xyz theme based on falcon
version: 1.0.0
assets:
 use_parent_assets: true
```

there are several javascript errors

![image](https://github.com/Oksydan/falcon/assets/4729231/16f6a47d-b020-4ade-a1fc-4452cd9f8a84)

### Node.js version

V20

### php version

v8.1

### OS and it's version

Linux

### Browsers

Chrome

### Required module/theme

theme 3.1.2

### Reproduction steps

```bash
1. Install falcon theme on PS 8.1.2
2. Create a basic child theme
3. Make sure, you have this update in core.js:
 before : 
o.default.cart = e.resp.cart;
   after 
o.default.cart = e.reason.cart;

4. see error console in browser

5. if you switch back to falcon theme, everything is fine.
4. See error
```

### Logs

```bash
Uncaught TypeError: r(...).emit is not a function
    at HTMLDocument.<anonymous> (core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:62:5703)
    at u (core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37:30297)
    at l (core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37:30599)
(anonym) @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:62
u @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
l @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
setTimeout (async)
j.readyException @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
(anonym) @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
u @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
l @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
setTimeout (async)
(anonym) @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
c @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
fireWith @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
fire @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
c @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
fireWith @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
l @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
setTimeout (async)
(anonym) @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
c @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
fireWith @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
fire @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
c @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
fireWith @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
ready @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
Q @ core.js?v=182be0c5cdcd5072bb1864cdee4d3d6e:37
```

**Comment by Oksydan** [comment]
Hi @Shoprunners,

Falcon theme isn't meant to work as child theme. 
If you are going to use it as child, you will lose every development feature.
What is your reason behind using child theme?
Why would you modify core.js? I don't understand that change at all.

**Comment by Oksydan** [comment]
Hi @Shoprunners 

You are like a first person that is asking about child theme feature. It will not work atm since we are not reading assets.yml of parent theme. It's more like a feature request than a bug report.

**Comment by Shoprunners** [comment]
> You are like a first person that is asking about child theme feature. It will not work atm since we are not reading assets.yml of parent theme. It's more like a feature request than a bug report.

Hi,
Okay, I see. So good to know. 
What is the best practice for you to keep the falcon theme uptodate in a live shop?

**Comment by Oksydan** [comment]
It depends tbh. Most of my stores are such a custom front end that I am only using Falcon as a starter for bigger project. If I need some new features, changes that were implemented in newer versions. I am just do it manually. 
This 3.1.2 version is last 3.X.X version of the theme. We are currently working rly hard to release version 4. There will be no easy way to upgrade from 3 to 4 with lots of changes compared to the previous version.

**Comment by Shoprunners** [comment]
Hi, thanks for the information.

**Comment by ePiliK** [comment]
Hi guys, I'm joining this topic.

I was looking for something similar, we are about to start an e-commerce site with around 20k products.

I was very intent on using your falcon theme which seems super fast with webpack.

At this point, what do you recommend waiting for release 4.0? instead of starting with this latest release of the 3?

Thanks in advance
