### ISSUE TITLE
🚀 [REQUEST] - is_shoppingcart new features

### ISSUE THREAD

**Issue by Oksydan** [Oksydan/falcon#320]
### Summary

TO DO:
 - [x] - add configuration to use dropdown cart and offcanvas cart
 - [x] - add configuration to display modal or not after adding to cart
 - [x] - make use of symfony autowire and autoconfigure features
 - [x] - droping prestashop < 8.1 support
 - [x] - https://github.com/Oksydan/falcon/issues/268

### Feature target required module/theme

is_shoppingcart

### Drawbacks

N/A

**Comment by benitko** [comment]
When? 🤩

**Comment by Oksydan** [comment]
Everything will be ready when we complete the entire Falcon 4 roadmap (including is_themecore 5 roadmap). Falcon 4 should be released in the first quarter of 2024.

**Comment by benitko** [comment]
Thank you for your work!

**Comment by Oksydan** [comment]
New version is almost ready. Every feature and bug fix pointed in this issue has been completed. I am closing this issue. We will be also implement new UI. There will be separated issue for this task.
