### ISSUE TITLE
🐛 [BUG] - [FIX]  Wrong ARIA ROLE in the product tab list

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#325]
### Description

Hi
I've found and fixed this error

https://github.com/PrestaShop/PrestaShop/issues/34504

the role="tab" should be moved from the a tag to the li tag

like so in the product-tabs.tpl
<li class="nav-item" role="tab">

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. go to google page speed
2. set the url of a product page with description and details
3. scroll down to the accessibility section about this role errors
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue.
I am not sure yet is it valid solution 🤔 according to bootstrap it should be:

```html
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Home</button>
  </li>
</ul>
```
I did small fixed on develop branch https://github.com/Oksydan/falcon/pull/328 - and product page now passes 100% lighthouse accessibility check.

I am closing this one. Thank you for once again.

**Comment by maofree** [comment]
Hi
today I confirm that solution is good. I'm using it on the real website and I've tested it
