### ISSUE TITLE
🐛 [BUG] - [FIX]  promo code click doesn't work, wrong class to the link

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#326]
### Description

Hi
it is necessary to replace "js-code" to "code" in this line like so
`<a href="#" class="code font-weight-bold">{$discount.code}</a> - {$discount.name}`

if not the click on the promo code doesn't copy the code on the cart summary

![1](https://github.com/Oksydan/falcon/assets/653230/660a4e2c-ab1c-43e1-b6cd-8c1e123aba44)
![2](https://github.com/Oksydan/falcon/assets/653230/00c549a7-4e90-4ce6-b1e7-aff387b9aa0c)

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. edit the cart-voucher.tpl
2. replace js-code to code
```

**Comment by yoan-webpremiere** [comment]
Hello,

I think the best thing would be to leave the j**s-code** class in cart-voucher.tpl and just change the **name** of the JS selector in "falcon/_dev/js/theme/components/**selectors.js**" (line.58) :
`discountCode: '.js-discount .code',`
to **` discountCode: '.js-discount .js-code',`**

**Comment by Oksydan** [comment]
Hi,

Thank you for your feedback. This problem has been fixed in version 4.0.0 on develop brach we can close this issue.
