### ISSUE TITLE
🐛 [BUG] - [FIX] in the checkout page the promo code is not added by click to the cart summary in ajax mode

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#327]
### Description

Hi
in the checkout page the click on the promo code doesn't work (after the previous fix the click works on cart summary but not in the checkout page)

in the checkout/_partials/header.tpl
it is necessary to add the displayTop hook

I have fixed using this code shown in the figure

![1](https://github.com/Oksydan/falcon/assets/653230/ac9e0fcb-41c2-47f6-837e-05a9d34597e4)
![2](https://github.com/Oksydan/falcon/assets/653230/d76a196a-1b92-49e3-8628-a4bf62620425)

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. add a promo code with set Highligh option
2. go to the checkout and try to click on this code
3. nothing happens
```

**Comment by Oksydan** [comment]
Hi @maofree 

Problem has been fixed in develop reach with recent core.js changes. I am closing this issue.
