### ISSUE TITLE
Some resource not correctly linked after first installation

### ISSUE THREAD

**Issue by ludimassa** [Oksydan/falcon#329]
### Description

Hi everyone,
I would start building my first falcon theme
By following the guide under xampp in a site without setting virtual host
I have the follow error only for some resource
![Screenshot 2023-11-14 181301](https://github.com/Oksydan/falcon/assets/46421917/977ba9ad-b62b-48dd-b236-314bbaf02310)

### Node.js version

18

### php version

7.4

### OS and it's version

windows

### Required module/theme

theme

### Reproduction steps

```bash
1. Install by following the guide under localhost/myprestashoppath/
```

**Comment by Oksydan** [comment]
Hi,

It clearly not a bug but problem with your configuration. What is your .env files?

**Comment by ludimassa** [comment]
PORT=3505
SERVER_ADDRESS=localhost
SITE_URL=http://localhost
PUBLIC_PATH=/dimassa812/themes/falcon/assets/

**Comment by Oksydan** [comment]
Hmm 🤔 this problem only occurs when you are working on your theme via dev command. For production build command it should work as expected. Be aware that it will required to build your theme with different public _path if your production/remote store environment isn't installed inside directory like your local environment.

**Comment by ludimassa** [comment]
After some configuration of vhost and some update in prestashop configuration table I haven't error
But what are the correct way for generate the production templete to move all file online?

**Comment by Oksydan** [comment]
You should run build script if our publicPath in your local env isn't different than in your production you don't have to do anything. Just run build and you can move your assets to production. If your production publicPath is different you have to build your theme with different configuration for env file. Second option is to build theme assets with your CI/CD proces - recommended.

**Comment by ludimassa** [comment]
thank
