### ISSUE TITLE
🐛 [BUG] - unknown tag 'appendParamToUrl' when customer is set to a new group and only this one

### ISSUE THREAD

**Issue by pibrom** [Oksydan/falcon#330]
### Description

Hello,
Here's the way i managed to create this bug :

- I created a customer group name 'pro' for B2B customers
- I affected this group to some customer, and **Only this new group**
When I try to access the web site, here's the PHP error : 
`PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:/home/www/themes/falcontheme/templates/_partials/stylesheets.tpl"  on line 29 "{$url = {appendParamToUrl url=$stylesheet.uri key=v value=$cssAssetHash}}" unknown tag 'appendParamToUrl' <--
  thrown in /home/www/themes/falcontheme/templates/_partials/stylesheets.tpl on line 29
`
If I assign my customer one of the 3 default groups (anaonymous, invite, customer), the problem doesn't occurs. This is very strange!

### Node.js version

v18.16.0

### php version

V8.0

### OS and it's version

Debian 11

### Browsers

Firefox, Chrome, Microsoft Edge

### Required module/theme

no

### Reproduction steps

```bash
1. Create at least one new customer group
2. Create one customer and assign him to this new groupe and only this one (don't forget to aloso assign default customer group)
3. Login with this customer account
4. And so on !
```

**Comment by pibrom** [comment]
Update of my bug request : even the modifier images_block does not functionnate in the described setting above.

**Comment by pibrom** [comment]
Nevermind, issue is simply occured because created groups weren't autorized to use is_themcore module...
The autorization of all your theme's modules by every customer group solved this issue that isn't one...

**Comment by Oksydan** [comment]
Hi @pibrom,

modules aren't added automatically to module_group database upon group creating. It's just working this way. 
I can close this issue since it's resolved. Feel free to open new one.
