### ISSUE TITLE
🐛 [BUG] - [Fix] writing error in customer/order-detail.tpl

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#334]
### Description

Hi

in the file
writing error in customer/order-detail.tpl
it is necessary to replace
Shipping infromations
with
Shipping informations

![1](https://github.com/Oksydan/falcon/assets/653230/7f10d1fc-9e91-4c74-8abf-d8a0b281af88)

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. look at the file customer/order-detail.tpl
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue. 
I will add this to version 4 roadmap.

**Comment by Oksydan** [comment]
Hi @maofree,

problem has been fixed on develop branch.
I am closing this issue. Thank you for your contribution.
