### ISSUE TITLE
🚀 [REQUEST] - have the possibility of easily choosing a font-family different from the default one

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#335]
### Summary

Hi
in some cases could be necessary to use a different font-family
just the possibility of having an input field where you can insert a string like this might be enough

https://fonts.googleapis.com/css2?family=Titillium+Web&display=swap

and another one to set the name of font-family

![1](https://github.com/Oksydan/falcon/assets/653230/d00a3c64-dce9-430a-ae87-f0270dbf5bf1)

if these two fields were filled in, then the font files present in the theme would not be loaded

bye

### Feature target required module/theme

is_themecore and theme

### Drawbacks

it is an option that would be appreciated by many, making the theme more flexible

**Comment by Oksydan** [comment]
Hi @maofree

This can be done with code. I don't intend to add too many things, such as styling, changing the font in BO.
The purpose of this project is a little different. We are not building this project to please merchants, but developers. If you want to change the font, add new files and use font-face.
BTW, using third-party fonts will always be worse than self-hosting in terms of performance.

**Comment by mohaidoss** [comment]
@Oksydan agree on the first part, but I doubt your statement about self-hosting fonts would be better in terms of performance. I think if we leverage cloudflare font preload (only applicable to google fonts API), you will easily gain >100ms at least.

**Comment by futurowebpl** [comment]
but you can use eg. Google Fonts in head.tpl - why do you need such a field - this is completely wrong way, you should load it properly, so that it is preload and compile.

it's simple.

this is a better way for you as a developer, because the client has no way to easily change the font without losing performance - so he has to pay you for a possible font change.

**Comment by mohaidoss** [comment]
@futurowebpl totally agree 😅, I just didn't agree on the last part for font preload. And my estimate of 100ms gain isn't actually that accurate.
