### ISSUE TITLE
🚀 [REQUEST] - Reduce the preview.png size

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#340]
### Summary

Hi
I've seen that the preview.png has a size of 1.7MB
lloking at the preview.png of classic theme, I can see that it has a width of 500px, however 1.7MB is very big :)
I pass a resize image

<img width="250" alt="preview" src="https://github.com/Oksydan/falcon/assets/653230/a0f9e7d6-ab9f-4f77-aa53-9b5e098ec522">

### Feature target required module/theme

theme

### Drawbacks

reduces the size of the theme

**Comment by Oksydan** [comment]
Hi @maofree,

thb it doesn't matter that much 😄. We will be using a new preview image for Falcon 4. I am going to close this issue because I am not going to release minor version of 3.X only to release new version with reduced size of preview image.
