### ISSUE TITLE
🐛 [BUG] - The preload tag is missing when the css compression is active

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#342]
### Description

Hi
I've seen that the preload tag is missing when the css compression is active, it is present only when it is disabled, but it has little importance since compressions are always active for sites in production

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

is_themecore, theme

### Reproduction steps

```bash
1. active the css compression
2. look at the source code of the front-office
```

**Comment by Oksydan** [comment]
Hi @maofree,

sorry but I am not able to reproduce the problem 🤔. What preload tag is missing? Fronts preload?

**Comment by maofree** [comment]
Hi
I show you two image, one when the css compression is active and one when is not
![1](https://github.com/Oksydan/falcon/assets/653230/4df9bbcd-8f3e-475e-92e0-a3fd39cec4e6)
![2](https://github.com/Oksydan/falcon/assets/653230/923c6027-c20d-4867-a7a6-2547de664b6f)

`<link rel="preload" href="xxx/assets/css/theme.css?v=9f61408e3afb633e50cdf1b20de6f466" as="style">`

`<link rel="stylesheet" href="xxx/assets/cache/theme-3e0a9856.css?v=9f61408e3afb633e50cdf1b20de6f466" type="text/css" media="all">`

it should have a preload like theme.css when it is without the compression

**Comment by maofree** [comment]
it works, I've seen that is necessary to active the option in the is_themecore
