### ISSUE TITLE
🐛 [BUG] - is_themecore doesn't create webp images

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#346]
### Description

HI
I've set the new theme on a real website
there is a problem on the webp images about the main logo and the brand logos

I think it is due from the missing Cwebp binary in the server, instead on my local server is present
I've request it from the hosting
but at this moment is set Imagick PHP extension

![11](https://github.com/Oksydan/falcon/assets/653230/3402b357-41d2-4f0e-8f10-3e1e084e7613)

in the htaccess I think is ok

on my local server works also with Imagick PHP extension

I don't understand what it depends on.
From what I see it doesn't seem to create webp images

![1](https://github.com/Oksydan/falcon/assets/653230/532b6c77-0d01-4990-a65b-34a2775f0613)

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

is_themecore

### Reproduction steps

```bash
1. I don't know
```

**Comment by Oksydan** [comment]
Hi @maofree,

you can go to `is_themecore/webp.php` file and add above `$webpGenerator->convertAndServe();`
this code:

```php
$webpGenerator->setDebugEnabled(true);
```
Then you can try to request image generation via. 
yourdomain.com/modules/is_themecore/webp.php?source=/{PATHTOYOURIMAGE}/{imagename}.webp.

It should display you stack trace and error log. 
My first thought, it might be related to permissions.

**Comment by maofree** [comment]
Hi
this problem is so strange
if I set this line on the browser the webp image is created
yourdomain.com/modules/is_themecore/webp.php?source={PATHTOYOURIMAGE}/{imagename}.webp

instead if I reload the page no

**Comment by Oksydan** [comment]
Hi @maofree,

we talked through e-mails about it. This is related to the environment, not the module itself. 
I am not experienced with light speed, unfortunately. I am going to close this issue. 
Feel free to post a comment when you resolve your problem.

**Comment by Oksydan** [comment]
Hi @maofree,

All I can tell about ETA is first quarter of 2024. There is so much stuff left to do and my 'spare time' isn't infinite. I do whatever I can to speed it up. New [menu module](https://github.com/Oksydan/is_mainmenu) is almost ready. I am rewriting shopping cart module ATM. I am still waiting for UX designer to provide new projects. There is so many factors that can delay ETA in time. Lack of sponsors are also huge factor that aren't allow me to spend that much time working on this project. I can't pay bills and feed my family with github stars 😞

**Comment by maofree** [comment]
Hi
yes I know March 2024
the release of version 4 was just to better understand what decision to make, whether to continue installing my version based on 3 or wait for 4. I will continue with 3 so I can protect the larger sites.
having made many modules for prestashop, after having updated them to use the new prestashop solutions, I will put some of them on Addons.
it is certainly my goal to be able to help you with financial support for the development of falcon, not only technical, I like long-lasting collaborations, because I like to plan developments and be grateful for the help you are giving me. Alone it would be a little complicated to manage, then I also like to learn from others. Surely for now you are ahead on many things, but in a few months I will have learned many new things and will be more useful.
Maybe I will talk to the larger company I follow for project support, I think I will soon change the graphics and he will notice the benefits of optimized graphics

**Comment by maofree** [comment]
a little while ago I saw how to support the project with sponsors, I'll organize myself :)

**Comment by pfgluigi** [comment]
Sorry for re-open this. But Im having a problem with the webp images

This is not my first Prestashop with Falcon Theme, but this is the first one with this problem.

In one server, I have 2 Prestashops (same PHP version). One of them its in production and working fine.
The second one its a copy of this first one.
I have reinstalled the theme and the only thing that does not work for me are the webp images.
I get a 500 error if I try to access an image.
Here one example:
Prestashop 1 (working): https://domain1.com/11-home_default/image.webp 
Prestashop 2 (notworking): https://domain2.com/11-home_default/image.webp 

I have tryed to get some logs from this:

> Hi @maofree,
> 
> you can go to `is_themecore/webp.php` file and add above `$webpGenerator->convertAndServe();` this code:
> 
> ```
> $webpGenerator->setDebugEnabled(true);
> ```
> 
> Then you can try to request image generation via. yourdomain.com/modules/is_themecore/webp.php?source={PATHTOYOURIMAGE}/{imagename}.webp.
> 
> It should display you stack trace and error log. My first thought, it might be related to permissions.

I have enabled the _PS_MODE_DEV_, and I get this error:

> Fatal error: Uncaught WebPConvert\Exceptions\InvalidInput\TargetNotFoundException: source argument missing in /var/www/domain2/modules/is_themecore/vendor/rosell-dk/webp-convert/src/Helpers/PathChecker.php:67 Stack trace: #0 /var/www/domain2/modules/is_themecore/vendor/rosell-dk/webp-convert/src/Helpers/PathChecker.php(85): WebPConvert\Helpers\PathChecker::checkAbsolutePathAndExists() #1 /var/www/domain2/modules/is_themecore/vendor/rosell-dk/webp-convert/src/Serve/ServeConvertedWebP.php(82): WebPConvert\Helpers\PathChecker::checkSourcePath() #2 [internal function]: WebPConvert\Serve\ServeConvertedWebP::serveOriginal() #3 /var/www/domain2/modules/is_themecore/vendor/rosell-dk/webp-convert/src/Serve/ServeConvertedWebPWithErrorHandling.php(78): call_user_func() #4 /var/www/domain2/modules/is_themecore/vendor/rosell-dk/webp-convert/src/Serve/ServeConvertedWebPWithErrorHandling.php(156): WebPConvert\Serve\ServeConvertedWebPWithErrorHandling::performFailAction() #5 /var/www/domain2/modules/is_themecore/vendor/rosell-dk/webp-convert/src/WebPConvert.php(81): WebPConvert\Serve\ServeConvertedWebPWithErrorHandling::serve() #6 /var/www/domain2/modules/is_themecore/src/Core/Webp/WebpGenerator.php(106): WebPConvert\WebPConvert::serveConverted() #7 /var/www/domain2/modules/is_themecore/webp.php(16): Oksydan\Module\IsThemeCore\Core\Webp\WebpGenerator->convertAndServe() #8 {main} thrown in /var/www/domain2/modules/is_themecore/vendor/rosell-dk/webp-convert/src/Helpers/PathChecker.php on line 67

What can be happening?
