### ISSUE TITLE
🐛 [BUG] - [FIX] is_imageslider wrong use of the legend field, it should be used for the alt_text

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#347]
### Description

Hi
I've seen that is_imageslider doesn't use the legend field in slider.tpl
for the alt_text is used slide.title, but should be slide.legend

![1](https://github.com/Oksydan/falcon/assets/653230/6dd019dd-0b91-4989-a232-c72d035e542c)

you could use a condition, where if the legend is not set then use the title, as happens for the alt_text of product images

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

is_imageslider

### Reproduction steps

```bash
1. look at the file slider.tpl
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue. 
I am adding it to `is_imageslider` epic for new version.

**Comment by Oksydan** [comment]
Hi @maofree,

this issue has been fixed here https://github.com/Oksydan/is_imageslider/pull/49 and it will be available in the next major version.
Thank you for your contribution.
