### ISSUE TITLE
🐛 [BUG] - [FIX] into ps_languageselector.tpl and ps_currencyselector.tpl it is necessary to change aria-labelledby to aria-label to avoid an accessibility error

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#348]
### Description

Hi
I've found with google page speed this error and fixed in this mode
following this guide, suggested by Google
https://dequeuniversity.com/rules/axe/4.7/select-name

aria-labelledby is used when there is a label with an id, like in classic theme
intead when there is not a reference label, it is necessary to set aria-label

I fix in this mode

`<select class="js-select-link custom-select" aria-label="{l s='Language' d='Shop.Istheme'}">`
`<select class="js-select-link custom-select" aria-label="{l s='Currency' d='Shop.Istheme'}">`

![1](https://github.com/Oksydan/falcon/assets/653230/231e53ac-89fa-4732-a9cb-15e684d512bb)

it is necessary to do it for both files
ps_currencyselector.tpl
ps_languageselector.tpl

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Look at ps_languageselector.tpl and check with google page speed in the accessibility section
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you creating an issue.
I am aware of some of the accessibility issues. I know there are many more things to do.
I plan to review the theme after implementing the new project in Falcon 4 to fix all / most of them.

**Comment by Oksydan** [comment]
Hi @maofree,

changes have been applied on develop branch.
I am closing this issue. Thank you for your contribution.
