### ISSUE TITLE
🚀 [REQUEST] - is_searchbar add a field to its configuration page to choose the number of items to show in the window

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#349]
### Summary

Hi
I think should be useful to add the possibility to set the number of items to show in the result window
in this mode I can show more than 6 items like 4 items in two rows

![1](https://github.com/Oksydan/falcon/assets/653230/688e3f8b-23ce-4665-a6bb-84d9a9a3e50b)

bye

### Feature target required module/theme

is_searchbar

### Drawbacks

adds more solutions for big websites

**Comment by Oksydan** [comment]
Hi @maofree,

I am adding this to `is_searchbar` module epic for new version.

**Comment by Oksydan** [comment]
Hi @maofree,

configuration has been added to the module and it will be available in next 4.0.0 version.
