### ISSUE TITLE
🐛 [BUG] - [FIX] is_searchbar small class fix

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#360]
### Description

Hi
in
_partials/modal-search.tpl
and
is_searchbar.tpl

it is necessary to replace "saerchModal" with "searchModal"

I a website there is a problem with mobile devices
the input search field doesn't appear in the modal. It happens only if I resize the browser's width
In other 2 websites all is ok, and also on my dev local site. If I copy their theme on it, I continue to get the same problem.
I think there is a condition that creates this problem on the last theme.
From the web tool with mobile option enabled, I can see that the div _mobile_search_from is void for mobile, in the others is with the form code.
I think it doesn't understand that I see it from a mobile device

If I disable the mobile device option from the chrome's webtool and I resize the width to 500px I can see the search bar in the modal popup

after a while I've seen that the problem is due from responsive.js from this line
prestashop.responsive.mobile = isMobile();
if I set
prestashop.responsive.mobile = true;
it works

prestashop.responsive.current_width = window.innerWidth;
prestashop.responsive.min_width = 768;
prestashop.responsive.mobile = isMobile();

the same problem is present for the facesearch module from mobile with the void modal

so it is due from window.innerWidth;
it is a basic javascript

it is so strange
the same theme with a different behavior about this point

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

is_searchbar

### Reproduction steps

```bash
1. look at into the two tpl files
```

**Comment by maofree** [comment]
into that code adding alert(window.innerWidth);
it gives 1716 instead 429

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue.
Since problem isn't related to module itself I am closing this issue.
That 'small' problem with typo in has been fixed on develop branch - https://github.com/Oksydan/is_searchbar/blob/develop/views/templates/hook/displayBeforeBodyClosingTag.tpl - new version is ready for Falcon 4.
