### ISSUE TITLE
🐛 [BUG] - [FIX] fixed a problem in product-cover-thumbnails.tpl to avoid contant duplications of displayAfterProductThumbs

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#362]
### Description

Hi
to avoid content duplications of modules that use displayAfterProductThumbs it is necessary to move
`{hook h='displayAfterProductThumbs' product=$product}`
inside the last closed div tag like below

![1](https://github.com/Oksydan/falcon/assets/653230/4e10dfb4-510f-4f79-bc87-aefd83a9983d)
![2](https://github.com/Oksydan/falcon/assets/653230/cf06a9c9-57c4-4fdd-bbe5-1667669cef91)

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. open the the file product-cover-thumbnails.tpl and compare it with this of classic theme about 
displayAfterProductThumbs
```

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue.
I was able to reproduce the problem. I am adding it to Falcon 4 roadmap.

**Comment by Oksydan** [comment]
Hi @maofree,

this problem has been fixed in the develop branch.
I am closing this issue. Thank you for your contribution.
