### ISSUE TITLE
🐛 [BUG] - Found a strange problem in the translations of is_shoppingcart 

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#363]
### Description

Hi
in my local server all is ok, instead on the real website, from the translations page I can see only the Admin section, the others three are missing

Isshoppingcart
Modalfail
Modalsuccess

![1](https://github.com/Oksydan/falcon/assets/653230/b509a330-a455-430e-ad29-f68cf7a95f96)

I think the installation was done in the same way, loading the folders into "modules", then loading the theme and installing the theme, then the modules are installed by themselves.
the module versions are the same

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

is_shoppingcart

### Reproduction steps

```bash
1. I don't know how to reproduce the problem
```

**Comment by Oksydan** [comment]
Hi @maofree,

unfortunately I wasn't able to reproduce the problem. 
Without reproduction steps I wan't be able to fix it.
I am closing this issue for now. If you find a way to reproduce it and it will be related to module not prestashop itself. Feel free to reopen this issue or create a new one.
