### ISSUE TITLE
🐛 [BUG] - is_themecore Attempted to call function "escapeshellarg" from namespace "WebPConvert\Convert\Converters".

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#368]
### Description

Hi
I cannot see the configuration page of is_themecore, in this case there is not the litespeed, the webp is disabled in prestashop (the problem is present also with webp enabled)

Attempted to call function "escapeshellarg" from namespace "WebPConvert\Convert\Converters".
[Symfony\Component\ErrorHandler\Error\UndefinedFunctionError 0]

the cwebp is installed, there is the 0.6.1 (now I asked to remove it)

![1](https://github.com/Oksydan/falcon/assets/653230/c2fc1f82-eaca-42df-a533-b3c732dd2870)
![2](https://github.com/Oksydan/falcon/assets/653230/74c25cf4-2b85-462e-abbf-1d3677f313db)
![3](https://github.com/Oksydan/falcon/assets/653230/8b1036d3-c8ec-435d-84f2-064fe9a01bd7)
![4](https://github.com/Oksydan/falcon/assets/653230/77e65733-81c7-49c6-bbee-82bdfa2ef763)

it is the first time that a get this type of error

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

is_themecore

### Reproduction steps

```bash
1. I think it is not possible to reproduce it on your server (probably it is due from cwebp version)
```

**Comment by maofree** [comment]
removing cwebp the error continue to be present in the configuration page of is_themecore

**Comment by Oksydan** [comment]
Hi @maofree 

Looks like php function [escapeshellarg](https://www.php.net/manual/en/function.escapeshellarg.php) is disabled on your server. You have to enable it.

**Comment by maofree** [comment]
Hi
ok thanks
it's a little vps, now I asked to activate it

**Comment by maofree** [comment]
problem solved in this mode, from the php settings

![image](https://github.com/Oksydan/falcon/assets/653230/8524ad61-fa81-4c19-9ddf-47568f15d9e0)

thanks
