### ISSUE TITLE
🐛 [BUG] - [FIX] missing js-product-customization class from product-customization.tpl

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#369]
### Description

Hi
I've seen that the class js-product-customization is missing from product-customization.tpl
it should be so

`<section class="product-customization js-product-customization my-3">`

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to product-customization.tpl
```

**Comment by Oksydan** [comment]
Hi @maofree 

thank you for creating an issue. This problem has been already fixed on develop branch and it will be available in next version.
I am closing this issue. Thank you for your contribution.
