### ISSUE TITLE
Icons are not displayed after installation. 

### ISSUE THREAD

**Issue by jbbrabec** [Oksydan/falcon#372]
### Description

![Screenshot_20240117_143815](https://github.com/Oksydan/falcon/assets/156926157/11e028fc-5831-4700-9eec-51a2f7d730a9)

The font files are there

`b3da@perca:~/htdocs/planko/eshop/themes/falcon/assets/fonts$ ls
icomoon-f03bd5823d38fe6e4a2b4f410de0ebbe.ttf
icomoon-f92bf140bac6feb5f2f3774eb849e9f2.woff
MaterialIcons-Regular-00b1fb69fb78ff50fd555de80b2fb45e.ttf
MaterialIcons-Regular-12a47ed5fd5585f0f4227fa035a1a607.woff2
MaterialIcons-Regular-479700ea91d964d295d75c6b67bd0b28.eot
MaterialIcons-Regular-f2a0933406f7830651524f477ba2f543.woff
roboto-v20-latin-ext_latin-500-0b45721325446d537b545d6224819ad4.woff2
roboto-v20-latin-ext_latin-500-e492ac63197a57e7f4d3bdb0001386ad.woff
roboto-v20-latin-ext_latin-700-1d1ef7788f0ff084b8811576cb59df57.woff2
roboto-v20-latin-ext_latin-700-8aba6dc5d991e4367d7ad685f85e5fe5.woff
roboto-v20-latin-ext_latin-italic-18cedfe87637eedb7b13bb08d2230e85.woff
roboto-v20-latin-ext_latin-italic-998c240e2a27f53b45db1c3b81080170.woff2
roboto-v20-latin-ext_latin-regular-5cb5c8f08bb4e6cb64c3b5b6115bf498.woff2
roboto-v20-latin-ext_latin-regular-ae804dc012b1b525547416df4b4524b3.woff
`

### Node.js version

-

### php version

8.1.27

### OS and it's version

-

### Required module/theme

-

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

**Comment by Oksydan** [comment]
Hi, 

what is your env file in theme and your shop_url table setup?

**Comment by jbbrabec** [comment]
Thank you for your response
What specifically do you mean by env file in theme?


![Screenshot_20240122_091158](https://github.com/Oksydan/falcon/assets/156926157/f16e7ad0-fd4d-43b5-8451-296264ed7632)

**Comment by Oksydan** [comment]
Did you follow installation steps. Did you initialize project with falcon-cli?

**Comment by Oksydan** [comment]
You are running develop script in remote server. Dev script is starting webpack dev server for given address under given port. You are starting your webpack dev server in http and your application runs oner https networks. That's a mismatch. You can run develop app instance over w/o ssl or enable ssl in webpack configuration for webpack dev server. I am not recommending developing theme on remote server. If you would like to build your theme instead of starting webpack dev server, please run build command. You can read more about scripts in documentation.

**Comment by jbbrabec** [comment]
Thanks for the advice. I ran the build command and everything is ok. I still need to learn how the webpack dev server works.

**Comment by Oksydan** [comment]
Hi @jbbrabec,

since this issue is resolved, I am closing this issue.
Feel free to open new one.
