### ISSUE TITLE
🚀 [REQUEST] - add use fetchpriority to is_imageslider

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#378]
### Summary

Hi @Oksydan 
now I'm reading something else, I don't know if it's correct, but given that Google page speed occasionally sees the presence of the second image in lazy loading, perhaps the problem can be solved by giving a lower priority to the images that are after the first

![1](https://github.com/Oksydan/falcon/assets/653230/070fc3a9-b16e-4129-98c0-47aa9ddbe869)

https://web.dev/articles/fetch-priority?hl=en

### Feature target required module/theme

is_imageslider

### Drawbacks

to reduce the problem on the second image views from google page speed

**Comment by Oksydan** [comment]
Hi @maofree,

thb it's not a problem at all. It's presented there coz probably animation is starting and second images is being loaded.
You shouldn't focus too much on the lighthouse score and concentrate on the core web vitals.
For a real user, not a lighthouse bot, it will be quite normal to download the second image when changing the slide and the third and so on.
We don't need to change anything here.

I am closing this issue but you can reopen this issue or create a new one  if necessary.
