### ISSUE TITLE
🚀 [REQUEST] - Add the arrows in the product-thumbs carousel

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#380]
### Summary

Hi
is it possible to add the arrows to the product-thumbs carousel?
I am asked above all to show that there are other hidden images that can be scrolled through.
in case a product has 10 images, this would not be understood by customers at first glance and they may not understand that there is a horizontal scrolling of those thumbnails

![0](https://github.com/Oksydan/falcon/assets/653230/6b5b75d3-3260-4695-8835-ad8da6f49f3a)

all you need is for the click to scroll the thumbnail carousel without having any effects on the large photos

bye

### Feature target required module/theme

theme

### Drawbacks

makes it intuitive that there are multiple photos in the product gallery and that there is horizontal scrolling of the thumbnails.

**Comment by maofree** [comment]
Hi
added editing ProductGallery.js

![44](https://github.com/Oksydan/falcon/assets/653230/18f2408f-def9-459d-bb23-a42850667565)

and adding the arrows inside product-cover-thumbnails.tpl

I think it is an useful thing to add by default

bye

**Comment by Oksydan** [comment]
Hi @maofree,

yes, it's good suggestion. 
I am adding this to Falcon 4.0.0 road map.

**Comment by Oksydan** [comment]
Hi @maofree,

this feature has been implemented on develop branch.
I am closing this issue. Thank you for your contribution.
