### ISSUE TITLE
🚀 [REQUEST] - Notification when click on add to cart button

### ISSUE THREAD

**Issue by sparh** [Oksydan/falcon#384]
### Summary

Hello
when customer click on the add to cart there is a small delay before the confirmation popup appears.
On your demo the delay is less long but on a big website it is longer (0.5 to 1s on my website).

It could be good to have something to let the customer know that the process is underway, for example a loading animation on the button or immediatly show the popup with a loading animation inside it.

### Feature target required module/theme

is_shoppingcart and theme

### Drawbacks

Some customer may think there is a problem and rage click on the button

**Comment by Oksydan** [comment]
Hi @sparh,

thank you for your suggestion. 
I am adding this to Falcon 4 roadmap.

**Comment by Oksydan** [comment]
Hi @sparh,

this feature has been implemented on develop branch.
I am closing this issue. Thank you for your contribution.
