### ISSUE TITLE
🐛 [BUG] - [FIX] passwords created from the reset page have problems with the next login

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#385]
### Description

Hi
Passwords created from the reset page may have problems if they are not complex.
this problem is not present in the "classic" theme, even if I enter a weak password, I can log in again, with a message "it is not well formatted".
the reason is due to the absence of the new password quality verification system, so the customer does not realize how it must be done.
there are two solutions, I insert the system to verify the strength of a password or do it in the "classic" theme where it lets the password be done even if they are weak

![2](https://github.com/Oksydan/falcon/assets/653230/2b4ee298-0e68-46a9-bdc4-705799ab2b93)
![3](https://github.com/Oksydan/falcon/assets/653230/285428e1-21c4-4a88-9564-16bafce426b0)

bye

### Node.js version

v18

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. go at login
2. push on the link "I don't remember the password"
3. set an email to get the reset link
4. push on the reset link
5. set a new password, but weak like "casetta"
6. do the log out
7. try to do the log in
8. you will get this error "it is not well formatted"

now try to do the same steps with the classic theme
```

**Comment by maofree** [comment]
Hi
problem fxed adding the new solution also for the reset password page

![1](https://github.com/Oksydan/falcon/assets/653230/ca8e0f8e-1af9-4df8-b89c-c5f06ef9f473)

[password-new.zip](https://github.com/Oksydan/falcon/files/14330600/password-new.zip)

I've fixed another little error, it is necessary to remplace
"alert alert-error"
to
"alert alert-danger"

bye

**Comment by Oksydan** [comment]
Hi @maofree,

thank you for creating an issue. I am adding this to Falcon 4 roadmap.

**Comment by Oksydan** [comment]
Hi @maofree,

this problem has been fixed on develop branch.
Thank you for your contribution.
